### ISSUE TITLE
GSHHS Download issues

### ISSUE THREAD

**Issue by greatrussian** [SciTools/cartopy#1011]
I am using cartopy to fetch the GSHHS filepath, and download if necessary. In doing so, I have come across 2 issues, which I think would be easy to fix.

### Issue 1: Call to shapereader.gshhs(scale, level) doesn't return appropriate level:
```
>>> import cartopy
>>> cartopy.io.shapereader.gshhs(scale='c', level=2)
'C:\\Anaconda35\\envs\\gis\\lib\\site-packages\\cartopy\\data\\shapefiles\\gshhs\\c\\GSHHS_c_L1.shp'
```
I believe this is because the code matches to any level and not just the requested level:
```
        repo_fname_pattern = os.path.join(config['repo_data_dir'],
                                          'shapefiles', 'gshhs', '{scale}',
                                          'GSHHS_{scale}_L?.shp')
```
Better would be:
```
        repo_fname_pattern = os.path.join(config['repo_data_dir'],
                                          'shapefiles', 'gshhs', '{scale}',
                                          'GSHHS_{scale}_L{level}.shp')
```
###Issue 2: Unable to download new files:
```
>>> cartopy.io.shapereader.gshhs(scale='i', level=1)
C:\Anaconda35\envs\gis\lib\site-packages\cartopy\io\__init__.py:264: DownloadWarning: Downloading: https://www.ngdc.noaa.gov/mgg/shorelines/data/gshhs/oldversions/version2.2.0/GSHHS_shp_2.2.0.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda35\envs\gis\lib\site-packages\cartopy\io\shapereader.py", line 378, in gshhs
    return gshhs_downloader.path(format_dict)
  File "C:\Anaconda35\envs\gis\lib\site-packages\cartopy\io\__init__.py", line 226, in path
    result_path = self.acquire_resource(target_path, format_dict)
  File "C:\Anaconda35\envs\gis\lib\site-packages\cartopy\io\shapereader.py", line 465, in acquire_resource
    self.acquire_all_resources(format_dict)
  File "C:\Anaconda35\envs\gis\lib\site-packages\cartopy\io\shapereader.py", line 439, in acquire_all_resources
    member = zfh.getinfo(member_path)
  File "C:\Anaconda35\envs\gis\lib\zipfile.py", line 1199, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'GSHHS_shp\\\\c\\\\GSHHS_c_L1.shp' in the archive"
```
This appears to be a Windows specific error, where ZipFile requires path to use forward slashes. Fix would be to replace '\\\\' with '/' prior to reading the zip.
`                member = zfh.getinfo(member_path.replace(os.sep,'/'))
`

**Comment by pelson** [comment]
Thanks for reporting @greatrussian. I agree completely - these both look like bugs.
Would you like to submit a PR to fix them?

**Comment by pelson** [comment]
Issue 2 was solved in #1083.
Issue 1 PR incoming.
