### ISSUE TITLE
shapely.errors.TopologicalError: The operation 'GEOSContains_r' could not be performed

### ISSUE THREAD

**Issue by akrherz** [SciTools/cartopy#1064]
### Description
A bad geometry leads to a shapely exception and thus cartopy failure

#### Code to reproduce

As with other issues like this, it takes me some time to create a reproducer, but figured I'd get the issue started anyway.

#### Traceback 

```python
ERROR:shapely.geos:TopologyException: side location conflict at -79.640000000045802 36.660000000002604
Traceback (most recent call last):
  File "q3_xhour.py", line 103, in <module>
    main(sys.argv)
  File "q3_xhour.py", line 99, in main
    doit(ts, int(argv[1]))
  File "q3_xhour.py", line 84, in doit
    cmap=nwsprecip())
  File "/opt/miniconda2/envs/prod/lib/python2.7/site-packages/pyiem/plot/geoplot.py", line 970, in contourf
    extend='both', transform=ccrs.PlateCarree())
  File "/opt/miniconda2/envs/prod/lib/python2.7/site-packages/cartopy/mpl/geoaxes.py", line 1397, in contourf
    if col.get_paths()])
  File "/opt/miniconda2/envs/prod/lib/python2.7/site-packages/matplotlib/collections.py", line 196, in get_datalim
    paths = [transform.transform_path_non_affine(p) for p in paths]
  File "/opt/miniconda2/envs/prod/lib/python2.7/site-packages/matplotlib/transforms.py", line 2499, in transform_path_non_affine
    return self._a.transform_path_non_affine(path)
  File "/opt/miniconda2/envs/prod/lib/python2.7/site-packages/cartopy/mpl/geoaxes.py", line 189, in transform_path_non_affine
    getattr(self, 'force_path_ccw', False))
  File "/opt/miniconda2/envs/prod/lib/python2.7/site-packages/cartopy/mpl/patch.py", line 212, in path_to_geos
    collection[-1][0].contains(geom.exterior)):
  File "/opt/miniconda2/envs/prod/lib/python2.7/site-packages/shapely/geometry/base.py", line 691, in contains
    return bool(self.impl['contains'](self, other))
  File "/opt/miniconda2/envs/prod/lib/python2.7/site-packages/shapely/predicates.py", line 18, in __call__
    self._check_topology(err, this, other)
  File "/opt/miniconda2/envs/prod/lib/python2.7/site-packages/shapely/topology.py", line 38, in _check_topology
    self.fn.__name__, repr(geom)))
shapely.errors.TopologicalError: The operation 'GEOSContains_r' could not be performed. Likely cause is invalidity of the geometry
<shapely.geometry.polygon.Polygon object at 0x7f7dce066290>
```

<details>
 <summary>Full environment definition</summary>

### Operating system

RHEL 7.5 x86 Workstation

### Cartopy version

0.16 + two of my own patches to increase shapely stability.

### conda list

```
# packages in environment at /opt/miniconda3/envs/prod:
#
# Name                    Version                   Build  Channel
affine                    2.2.0                    py36_0  
alabaster                 0.7.10           py36h306e16b_0  
apiclient                 1.0.3                     <pip>
appdirs                   1.4.3                    py36_0  
argh                      0.26.2                   py36_1    conda-forge
asn1crypto                0.24.0                   py36_0  
astroid                   1.6.3                    py36_0  
attrs                     17.4.0                   py36_0  
automat                   0.6.0            py36ha140c00_0  
babel                     2.5.3                    py36_0  
backports                 1.0              py36hfa02d7e_1  
backports.functools_lru_cache 1.5                      py36_0    conda-forge
backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2  
backports_abc             0.5                      py36_0    conda-forge
beautifulsoup4            4.6.0            py36h49b8c8c_1  
biggus                    0.15.0                   py36_0    conda-forge
blas                      1.0                         mkl    conda-forge
bleach                    2.1.3                    py36_0  
boost                     1.65.1                   py36_4  
boost-cpp                 1.65.1               h14c3975_4  
boto3                     1.7.4                    py36_0  
botocore                  1.10.4                   py36_0  
bzip2                     1.0.6                h9a117a8_4  
ca-certificates           2018.03.07                    0  
cairo                     1.14.12              h77bcde2_0  
cartopy                   0.16.0           py36hf32a85a_0  
cdo                       1.9.3                         0    conda-forge
certifi                   2018.4.16                py36_0  
cf_units                  1.2.0                    py36_0    conda-forge
cffi                      1.11.5           py36h9745a5d_0  
chardet                   3.0.4            py36h0f667ec_1  
click                     6.7              py36h5253387_0  
click-plugins             1.0.3                    py36_0  
cligj                     0.4.0                    py36_0  
commonmark                0.7.5                    py36_0  
constantly                15.1.0                   py36_0  
coverage                  4.5.1            py36h14c3975_0  
cryptography              2.2.2            py36h14c3975_0  
curl                      7.59.0               h84994c4_0  
cycler                    0.10.0           py36h93f1223_0  
cython                    0.28.2           py36h14c3975_0  
dbus                      1.13.2               hc3f9b76_0  
decorator                 4.3.0                    py36_0  
descartes                 1.1.0            py36h2f9c1c0_0  
doc8                      0.8.0                    py36_0    conda-forge
docutils                  0.14             py36hb0f60f5_0  
dropbox                   8.8.1                    py36_0  
eccodes                   2.7.0                         0    conda-forge
ecmwf_grib                1.26.0                        0    conda-forge
entrypoints               0.2.3            py36h1aec115_2  
ephem                     3.7.6.0          py36h14c3975_1  
esmf                      7.1.0r                        0    conda-forge
et_xmlfile                1.0.1            py36hd6bccc3_0  
expat                     2.2.5                he0dffb1_0  
fftw                      3.3.4                         0    HCC
filelock                  3.0.4                    py36_0  
fiona                     1.7.10           py36h48a52f0_0  
flake8                    3.5.0                    py36_1  
fontconfig                2.12.6               h49f89f6_0  
freeglut                  3.0.0                hf484d3e_5  
freetype                  2.8                  hab7d2ae_1  
freexl                    1.0.5                h14c3975_0  
fribidi                   1.0.2                h14c3975_0  
future                    0.16.0                   py36_1  
gdal                      2.2.2            py36hc209d97_1  
gdata                     3.0.0                     <pip>
geojson                   2.3.0                      py_0    conda-forge
geopandas                 0.3.0            py36h2f9c1c0_0  
geos                      3.6.2                heeff764_2  
geotiff                   1.4.2                h8e81d37_0  
gettext                   0.19.8.1             hd7bead4_3  
giflib                    5.1.4                h26a3ec6_1  
glib                      2.53.6               h5d9569c_2  
gmp                       6.1.2                h6c8ec71_1  
google-api-python-client  1.6.6                     <pip>
graphite2                 1.3.11               hf63cedd_1  
gsl                       2.2.1                h0c605f7_3  
gst-plugins-base          1.12.4               h33fb286_0  
gstreamer                 1.12.4               hb53b477_0  
harfbuzz                  1.7.6                hc5b324e_0  
hdf4                      4.2.13               h3ca952b_2  
hdf5                      1.10.1               h9caa474_1  
html5lib                  1.0.1            py36h2f9c1c0_0  
httplib2                  0.11.1                   py36_0    conda-forge
hyperlink                 18.0.0                   py36_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.6              py36h82fb2a8_1  
incremental               17.5.0           py36hff7e2ee_0  
intel-openmp              2018.0.0                      8  
isort                     4.3.4                    py36_0  
jasper                    1.900.1              hd497a04_4  
jdcal                     1.4                      py36_0  
jenks                     1.0                       <pip>
jmespath                  0.9.3            py36hd3948f9_0  
jpeg                      9b                   h024ee3a_2  
json-c                    0.12.1               ha6a3662_2  
jsonschema                2.6.0            py36h006f8b5_0  
kealib                    1.4.7                h79811e5_5  
kiwisolver                1.0.1            py36h764f252_0  
krb5                      1.14.2               hcdc1b81_6  
lazy-object-proxy         1.3.1            py36h10fcdad_0  
libboost                  1.65.1               habcd387_4  
libcurl                   7.59.0               h1ad7b7a_0  
libdap4                   3.19.0               h5bd89bb_2  
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                hdf63c60_3  
libgdal                   2.2.2                h804cdde_1  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                hdf63c60_3  
libglu                    9.0.0                h0c0bdc1_1  
libkml                    1.3.0                h9d32c78_3  
libnetcdf                 4.4.1.1              h816af47_8  
libopenblas               0.2.20               h9ac9557_4  
libpng                    1.6.34               hb9fc6fc_0  
libpq                     9.6.6                h4e02ad2_0  
libspatialindex           1.8.5                h20b78c2_2  
libspatialite             4.3.0a              h72746d6_18  
libssh2                   1.8.0                h9cfc8f7_4  
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                h28f6b97_0  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                hf84eae3_0  
libxslt                   1.1.32               h1312cb7_0  
lxml                      4.2.1            py36h23eabaa_0  
lzo                       2.10                 h49e0be7_2  
matplotlib                2.2.2            py36h0e671d2_1  
mccabe                    0.6.1            py36h5ad9710_1  
metar                     1.5.0                     <pip>
metpy                     0.7.0                    py36_0    conda-forge
mkl                       2018.0.2                      1  
mkl_fft                   1.0.1            py36h3010b51_0  
mkl_random                1.0.1            py36h629b387_0  
mock                      2.0.0            py36h3c5bf6c_0  
mod-wsgi                  4.6.4                     <pip>
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1                         0    conda-forge
munch                     2.3.1                    py36_0  
nco                       4.7.4                         0    conda-forge
ncurses                   6.0                  h9df7e31_2  
netcdf-fortran            4.4.4                         6    conda-forge
netcdf4                   1.3.1            py36hfd655bd_2  
nose                      1.3.7            py36hcdf7029_2  
numexpr                   2.6.4            py36hc4a3f9a_0  
numpy                     1.14.2           py36hdbf6ddf_1  
nwnserver                 0.2                       <pip>
oauth2client              4.1.2                    py36_0    conda-forge
odfpy                     1.3.6                     <pip>
olefile                   0.45.1                   py36_0  
openblas                  0.2.20                        4  
openblas-devel            0.2.20                        4  
openjpeg                  2.3.0                hef292c2_0  
openssl                   1.0.2o               h20670df_0  
owslib                    0.16.0                   py36_0  
pandas                    0.22.0           py36hf484d3e_0  
pango                     1.42.0               h377f3fa_0  
paste                     2.0.3            py36h9fb3c17_0  
pbr                       4.0.2                    py36_0  
pcre                      8.42                 h439df22_0  
pep8                      1.7.1                    py36_0  
pika                      0.11.2                   py36_0    conda-forge
pillow                    5.1.0            py36h3deb7b8_0  
pint                      0.8.1                    py36_0    conda-forge
pip                       9.0.3                    py36_0  
pixman                    0.34.0               hceecf20_3  
poppler                   0.60.1               hc909a00_0  
poppler-data              0.4.8                hf2eda46_0  
postgresql                9.6.6                h95429c6_1  
proj4                     4.9.3                hc8507d1_7  
psycopg2                  2.7.4            py36hb7f436b_0  
py-boost                  1.65.1           py36hf484d3e_4  
pyasn1                    0.4.2            py36h4d1db45_0  
pyasn1-modules            0.2.1            py36hc893066_0  
pycodestyle               2.3.1            py36hf609f19_0  
pycparser                 2.18             py36hf9f622e_1  
pyepsg                    0.3.2            py36h1c26317_0  
pyflakes                  1.6.0            py36h7bd6a15_0  
pygrib                    2.0.2                    py36_3    conda-forge
pyIEM                     0.8.0                     <pip>
pyLDM                     0.0.4                     <pip>
pylint                    1.8.4                    py36_0  
pyopenssl                 17.5.0           py36h20ba746_0  
pypandoc                  1.4                       <pip>
pyparsing                 2.2.0            py36hee85983_1  
pyproj                    1.9.5.1                  py36_0  
pyqt                      5.9.2            py36h751905a_0  
PyRSS2Gen                 1.1                       <pip>
pysal                     1.14.3                   py36_0  
pyshp                     1.2.12           py36h04d6e4e_0  
pysocks                   1.6.8                    py36_0  
python                    3.6.5                hc3d631a_1  
python-dateutil           2.6.1            py36h88d3b88_1  
python-memcached          1.59                     py36_0  
pytz                      2018.4                   py36_0  
qt                        5.9.4                h4e5bff0_0  
rasterio                  0.36.0           py36hd410cfe_1  
rasterstats               0.12.1                     py_0    conda-forge
readline                  7.0                  ha6073c6_4  
requests                  2.18.4           py36he2e5f8d_1  
requests-toolbelt         0.8.0                    py36_0  
restructuredtext_lint     1.1.3                      py_0    conda-forge
rrdtool                   0.1.13                    <pip>
rsa                       3.4.2                    py36_0    conda-forge
rtree                     0.8.3            py36h2f9c1c0_0  
s3transfer                0.1.13                   py36_0  
scipy                     1.0.1            py36hfc37229_0  
setuptools                39.0.1                   py36_0  
setuptools-markdown       0.2                       <pip>
shapely                   1.6.4            py36h0c48222_0  
simplejson                3.14.0           py36h14c3975_0  
sip                       4.19.8           py36hf484d3e_0  
six                       1.11.0           py36h372c433_1  
smartsheet-python-sdk     1.0.2.dev1+gca2a053           <pip>
snuggs                    1.4.1            py36h2e8bf8d_0  
sqlalchemy                1.2.7            py36h6b74fdf_0  
sqlite                    3.23.1               he433501_0  
stevedore                 1.28.0                     py_0    conda-forge
tk                        8.6.7                hc745277_3  
tlslite                   0.4.9                     <pip>
tornado                   5.0.2                    py36_0  
tqdm                      4.23.0                   py36_0  
twisted                   17.5.0                   py36_0  
udunits2                  2.2.25               hd30922c_1  
Unidecode                 1.0.22                    <pip>
unixodbc                  2.3.6                h1bed415_0  
uritemplate               3.0.0                    py36_0    conda-forge
urllib3                   1.22             py36hbe7ace6_0  
util-linux                2.21                          0  
webencodings              0.5.1            py36h800622e_1  
wheel                     0.31.0                   py36_0  
windrose                  1.6                       <pip>
wordcloud                 1.4.1                    py36_0    conda-forge
wrapt                     1.10.11          py36h28b7045_0  
xerces-c                  3.2.1                hac72e42_0  
xlrd                      1.1.0            py36h1db9f0c_1  
xlsxwriter                1.0.4                    py36_0  
xlwt                      1.3.0            py36h7b00a1f_0  
xz                        5.2.3                h5e939de_4  
zlib                      1.2.11               ha838bed_2  
zope                      1.0                      py36_0  
zope.interface            4.5.0            py36h14c3975_0  
```

### pip list

```
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
affine (2.2.0)
alabaster (0.7.10)
apiclient (1.0.3)
appdirs (1.4.3)
argh (0.26.2)
asn1crypto (0.24.0)
astroid (1.6.3)
attrs (17.4.0)
Automat (0.6.0)
Babel (2.5.3)
backports-abc (0.5)
backports.functools-lru-cache (1.5)
backports.shutil-get-terminal-size (1.0.0)
beautifulsoup4 (4.6.0)
Biggus (0.15.0)
bleach (2.1.3)
boto3 (1.7.4)
botocore (1.10.4)
Cartopy (0.16.0)
certifi (2018.4.16)
cf-units (1.2.0)
cffi (1.11.5)
chardet (3.0.4)
click (6.7)
click-plugins (1.0.3)
cligj (0.4.0)
CommonMark (0.7.5)
constantly (15.1.0)
coverage (4.5.1)
cryptography (2.2.2)
cycler (0.10.0)
Cython (0.28.2)
decorator (4.3.0)
descartes (1.1.0)
doc8 (0.8.0)
docutils (0.14)
dropbox (8.8.1)
entrypoints (0.2.3)
ephem (3.7.6.0)
et-xmlfile (1.0.1)
filelock (3.0.4)
Fiona (1.7.10)
flake8 (3.5.0)
future (0.16.0)
GDAL (2.2.2)
gdata (3.0.0)
geojson (2.3.0)
geopandas (0.3.0)
google-api-python-client (1.6.6)
html5lib (1.0.1)
httplib2 (0.11.1)
hyperlink (18.0.0)
idna (2.6)
incremental (17.5.0)
isort (4.3.4)
jdcal (1.4)
jenks (1.0)
jmespath (0.9.3)
jsonschema (2.6.0)
kiwisolver (1.0.1)
lazy-object-proxy (1.3.1)
lxml (4.2.1)
matplotlib (2.2.2)
mccabe (0.6.1)
metar (1.5.0)
MetPy (0.7.0)
mkl-fft (1.0.0)
mkl-random (1.0.1)
mock (2.0.0)
mod-wsgi (4.6.4)
munch (2.3.1)
netCDF4 (1.3.1)
nose (1.3.7)
numexpr (2.6.4)
numpy (1.14.2)
nwnserver (0.2)
oauth2client (4.1.2)
odfpy (1.3.6)
olefile (0.45.1)
OWSLib (0.16.0)
pandas (0.22.0)
Paste (2.0.3)
pbr (4.0.2)
pep8 (1.7.1)
pika (0.11.2)
Pillow (5.1.0)
Pint (0.8.1)
pip (9.0.3)
psycopg2 (2.7.4)
pyasn1 (0.4.2)
pyasn1-modules (0.2.1)
pycodestyle (2.3.1)
pycparser (2.18)
pyepsg (0.3.2)
pyflakes (1.6.0)
pygrib (2.0.2)
pyIEM (0.8.0)
pyLDM (0.0.4)
pylint (1.8.4)
pyOpenSSL (17.5.0)
pypandoc (1.4)
pyparsing (2.2.0)
pyproj (1.9.5.1)
PyRSS2Gen (1.1)
PySAL (1.14.3)
pyshp (1.2.12)
PySocks (1.6.8)
python-dateutil (2.6.1)
python-memcached (1.59)
pytz (2018.4)
rasterio (0.36.0)
rasterstats (0.12.1)
requests (2.18.4)
requests-toolbelt (0.8.0)
restructuredtext-lint (1.1.3)
rrdtool (0.1.13)
rsa (3.4.2)
Rtree (0.8.3)
s3transfer (0.1.13)
scipy (1.0.1)
setuptools (39.0.1)
setuptools-markdown (0.2)
Shapely (1.6.4.post1)
simplejson (3.14.0)
six (1.11.0)
smartsheet-python-sdk (1.0.2.dev1+gca2a053)
snuggs (1.4.1)
SQLAlchemy (1.2.7)
stevedore (1.28.0)
tlslite (0.4.9)
tornado (5.0.2)
tqdm (4.23.0)
Twisted (17.5.0)
twittytwister (0.1.3)
Unidecode (1.0.22)
uritemplate (3.0.0)
urllib3 (1.22)
webencodings (0.5.1)
wheel (0.31.0)
windrose (1.6)
wordcloud (1.4.1)
wrapt (1.10.11)
xlrd (1.1.0)
XlsxWriter (1.0.4)
xlwt (1.3.0)
zope.interface (4.5.0)
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```

</details>

**Comment by QuLogic** [comment]
So were you able to find a simple reproducer?

**Comment by QuLogic** [comment]
Have you tried with 0.17.0?

**Comment by lkilcher** [comment]
I'll try that. In the meantime, I moved this to #1230 since the error is a bit different.
