### ISSUE TITLE
Missing Cython from install_requires..... again.

### ISSUE THREAD

**Issue by colllin** [SciTools/cartopy#1095]
When installing v0.16.0:

```
Collecting cartopy (from mypackage==0.0.0)
  Downloading https://files.pythonhosted.org/packages/f5/7a/4a16db7c81f11b3c5889c5b913d9a5724c704a6947c5a87ec59c4a8985ac/Cartopy-0.16.0.tar.gz (8.8MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-install-m56jwtye/cartopy/setup.py", line 47, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-m56jwtye/cartopy/setup.py", line 49, in <module>
        raise ImportError('Cython 0.15.1+ is required to install cartopy.')
    ImportError: Cython 0.15.1+ is required to install cartopy.
```

**Comment by Demetrio92** [comment]
#1112
