### ISSUE TITLE
Proj4Error when creating a CRS using a proj4 string

### ISSUE THREAD

**Issue by JimBiardCics** [SciTools/cartopy#1229]
### Description
A Proj4Error is thrown when creating a CRS using a proj4 string. This works in 0.15.0, but fails in 0.17.0.
There is no error if no Globe instance is provided when creating the CRS.

#### Code to reproduce
```
import cartopy.crs as crs


class GenericCRS(crs.CRS):
    pass

params = {
    'proj'  : 'lcc',
    'lon_0' : -107.0,
    'lat_0' : 50.0,
    'lat_1' : 50.0,
    'lat_2' : 50.0,
    'x_0'   : 5632642.22547,
    'y_0'   : 4612545.65137
}

gp = {
    'ellipse'        : 'sphere',
    'semimajor_axis' : 6378470.0,
    'flattening'     : 0.0
}


g = crs.Globe(**gp)

a = GenericCRS(params, g)

print a
```

#### Traceback 

```
Traceback (most recent call last):
  File "testCRS.py", line 26, in <module>
    a = GenericCRS(params, g)
  File "lib/cartopy/_crs.pyx", line 181, in cartopy._crs.CRS.__init__
cartopy._crs.Proj4Error: Error from proj: argument not numerical or out of range
```

<details>
 <summary>Full environment definition</summary>

### Operating system
Multiple
- Mac OSX 10.13.6
- SUSE Linux Enterprise Server 12 SP3

### Cartopy version
0.17.0

### conda list

```
asn1crypto                0.24.0                py27_1003    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.5                        py_1    conda-forge
backports_abc             0.5                        py_1    conda-forge
blas                      1.1                    openblas    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.14.12              h276e583_5    conda-forge
cartopy                   0.17.0           py27h7547761_1    conda-forge
certifi                   2018.11.29            py27_1000    conda-forge
cffi                      1.11.5           py27h5e8e0c9_1    conda-forge
cftime                    1.0.2.1          py27h7eb728f_0    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
cryptography              2.3.1            py27hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                 py27_1000    conda-forge
curl                      7.62.0               h74213dd_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
fontconfig                2.13.1               hce039c3_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
futures                   3.2.0                 py27_1000    conda-forge
geos                      3.6.2                hfc679d8_4    conda-forge
gettext                   0.19.8.1             h1f1d5ed_1    conda-forge
glib                      2.56.2               h464dc38_1    conda-forge
hdf4                      4.2.13               h951d187_2    conda-forge
hdf5                      1.10.3               hc401514_2    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                   py27_1002    conda-forge
ipaddress                 1.0.22                     py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
kiwisolver                1.0.1            py27h2d50403_2    conda-forge
krb5                      1.16.2               hbb41f41_0    conda-forge
libcurl                   7.62.0               hbdb9355_0    conda-forge
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libnetcdf                 4.6.1               h350cafa_11    conda-forge
libpng                    1.6.36               ha92aebf_0    conda-forge
libssh2                   1.8.0                h5b517e9_3    conda-forge
libtiff                   4.0.10               he6b73bb_0    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
libxslt                   1.1.32               h88dbc4e_2    conda-forge
lxml                      4.2.5            py27hc9114bc_0    conda-forge
matplotlib                2.2.3            py27h0e0179f_0    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
netcdf4                   1.4.2            py27hac939d9_0    conda-forge
numpy                     1.15.1          py27_blas_openblashd3ea46f_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
owslib                    0.17.0                     py_0    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
pillow                    5.3.0            py27hc736899_0    conda-forge
pip                       18.1                  py27_1000    conda-forge
pixman                    0.34.0               h470a237_3    conda-forge
proj4                     5.2.0                h470a237_1    conda-forge
pycairo                   1.18.0           py27h4d1f301_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pykdtree                  1.3.1            py27h7eb728f_2    conda-forge
pyopenssl                 18.0.0                py27_1000    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyproj                    1.9.5.1          py27h429999c_7    conda-forge
pyshp                     2.0.0                      py_0    conda-forge
pysocks                   1.6.8                 py27_1002    conda-forge
python                    2.7.15               h33da82c_6    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.7                     py_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.20.1                py27_1000    conda-forge
scipy                     1.1.0           py27_blas_openblash7943236_201    conda-forge
setuptools                40.6.2                   py27_0    conda-forge
shapely                   1.6.4            py27h164cb2d_1    conda-forge
singledispatch            3.4.0.3               py27_1000    conda-forge
six                       1.11.0                py27_1001    conda-forge
sqlite                    3.26.0               hb1c47c0_0    conda-forge
subprocess32              3.5.3            py27h470a237_0    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
tornado                   5.1.1            py27h470a237_0    conda-forge
urllib3                   1.23                  py27_1001    conda-forge
wheel                     0.32.3                   py27_0    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

### pip list

```
asn1crypto                    0.24.0     
backports-abc                 0.5        
backports.functools-lru-cache 1.5        
Cartopy                       0.17.0     
certifi                       2018.11.29 
cffi                          1.11.5     
cftime                        1.0.2.1    
chardet                       3.0.4      
cryptography                  2.3.1      
cryptography-vectors          2.3.1      
cycler                        0.10.0     
enum34                        1.1.6      
functools32                   3.2.3.post2
futures                       3.2.0      
idna                          2.7        
ipaddress                     1.0.22     
kiwisolver                    1.0.1      
lxml                          4.2.5      
matplotlib                    2.2.3      
netCDF4                       1.4.2      
numpy                         1.15.1     
olefile                       0.46       
OWSLib                        0.17.0     
Pillow                        5.3.0      
pip                           18.1       
pycairo                       1.18.0     
pycparser                     2.19       
pyepsg                        0.4.0      
pykdtree                      1.3.1      
pyOpenSSL                     18.0.0     
pyparsing                     2.3.0      
pyproj                        1.9.5.1    
pyshp                         2.0.0      
PySocks                       1.6.8      
python-dateutil               2.7.5      
pytz                          2018.7     
requests                      2.20.1     
scipy                         1.1.0      
setuptools                    40.6.2     
Shapely                       1.6.4.post1
singledispatch                3.4.0.3    
six                           1.11.0     
subprocess32                  3.5.3      
tornado                       5.1.1      
urllib3                       1.23       
wheel                         0.32.3
```

</details>

**Comment by QuLogic** [comment]
The lcc projection does not [support f(lattening) as a parameter](https://proj4.org/operations/projections/lcc.html).

**Comment by JimBiardCics** [comment]
Thanks for the suggestion! I checked and found that if I leave off the flattening the code above works. I also found that the code works if I specify a flattening of 1.0e-30. So that's a workaround, but there's still a problem.

The error and the workaround indicate that cartopy (or some underlying library) is assuming that a flattening value of zero is out of range. As you can see in the [Wikipedia article](https://en.wikipedia.org/wiki/Lambert_conformal_conic_projection), the basic projection equations are for a spherical earth, with the ellipsoidal case described as 'more involved'. The more involved case devolves to the spherical case when the flattening is zero. So zero is not an out of range value. This did not produce an error in cartopy 0.15.0.

It should not be an error to specify these parameters to Globe, nor to use them with any given projection (except in some case where a projection is not defined for a sphere).

**Comment by pelson** [comment]
This error is coming from proj itself: ``cartopy._crs.Proj4Error: Error from proj: argument not numerical or out of range``. There isn't anything that cartopy should be doing differently here - we defer entirely to proj as to what is valid input, so if it were enhanced to support flattening=0, it would "just work" in cartopy.

I'm going to go ahead an close this one out, as there is nothing to be done on the cartopy end.

Thanks for providing good detail in the issue report, and following up with further information so promptly! 👍
