### ISSUE TITLE
Topologicalerror GEOSIntersection_r

### ISSUE THREAD

**Issue by lkilcher** [SciTools/cartopy#1230]
While trying to plot the Hawaiian Islands using an AlbersEqualArea projection, I'm getting a `Topologicalerror: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0xb22f65e10>`. At first I thought this was the same as #1064, but it's a slightly different error.

Here is code that reproduces the error on my system:

    import matplotlib.pyplot as plt
    from cartopy import crs
    import cartopy.feature as cfeature

    pc = crs.PlateCarree()

    proj = crs.AlbersEqualArea(
        central_longitude=-157,
        central_latitude=21,
        standard_parallels=[20, 30]
    )

    fig = plt.figure(1)
    fig.clf()
    ax = plt.axes(projection=proj)
    ax.set_extent([-166, -150, 15, 27], crs=pc)
    ax.add_feature(cfeature.LAND.with_scale('50m'))

    fig.show()

Any thoughts?

<details><summary>Full Traceback</summary>

    /Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/cartopy/mpl/feature_artist.py:136: UserWarning: Unable to determine extent. Defaulting to global.
    warnings.warn('Unable to determine extent. Defaulting to global.')
    No handlers could be found for logger "shapely.geos"
    Exception in Tkinter callback
    Traceback (most recent call last):
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
        return self.func(*args)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/backends/_backend_tk.py", line 227, in resize
        self.draw()
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 12, in draw
        super(FigureCanvasTkAgg, self).draw()
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 437, in draw
        self.figure.draw(self.renderer)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
        return draw(artist, renderer, *args, **kwargs)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/figure.py", line 1493, in draw
        renderer, self, artists, self.suppressComposite)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
        a.draw(renderer)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
        return draw(artist, renderer, *args, **kwargs)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/cartopy/mpl/geoaxes.py", line 385, in draw
        inframe=inframe)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
        return draw(artist, renderer, *args, **kwargs)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2635, in draw
        mimage._draw_list_compositing_images(renderer, self, artists)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
        a.draw(renderer)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
        return draw(artist, renderer, *args, **kwargs)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/cartopy/mpl/feature_artist.py", line 163, in draw
        geom, feature_crs)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/cartopy/crs.py", line 181, in project_geometry
        return getattr(self, method_name)(geometry, src_crs)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/cartopy/crs.py", line 297, in _project_multipolygon
        r = self._project_polygon(geom, src_crs)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/cartopy/crs.py", line 336, in _project_polygon
        return self._rings_to_multi_polygon(rings, is_ccw)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/cartopy/crs.py", line 580, in _rings_to_multi_polygon
        polygon = boundary_poly.intersection(polygon)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/shapely/geometry/base.py", line 620, in intersection
        return geom_factory(self.impl['intersection'](self, other))
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/shapely/topology.py", line 70, in __call__
        self._check_topology(err, this, other)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/shapely/topology.py", line 38, in _check_topology
        self.fn.__name__, repr(geom)))
    TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0xb22f65e10>
    Exception in Tkinter callback
    Traceback (most recent call last):
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
        return self.func(*args)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/lib-tk/Tkinter.py", line 592, in callit
        func(*args)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/backends/_backend_tk.py", line 310, in idle_draw
        self.draw()
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 12, in draw
        super(FigureCanvasTkAgg, self).draw()
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 437, in draw
        self.figure.draw(self.renderer)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
        return draw(artist, renderer, *args, **kwargs)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/figure.py", line 1493, in draw
        renderer, self, artists, self.suppressComposite)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
        a.draw(renderer)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
        return draw(artist, renderer, *args, **kwargs)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/cartopy/mpl/geoaxes.py", line 385, in draw
        inframe=inframe)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
        return draw(artist, renderer, *args, **kwargs)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2635, in draw
        mimage._draw_list_compositing_images(renderer, self, artists)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
        a.draw(renderer)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
        return draw(artist, renderer, *args, **kwargs)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/cartopy/mpl/feature_artist.py", line 163, in draw
        geom, feature_crs)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/cartopy/crs.py", line 181, in project_geometry
        return getattr(self, method_name)(geometry, src_crs)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/cartopy/crs.py", line 297, in _project_multipolygon
        r = self._project_polygon(geom, src_crs)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/cartopy/crs.py", line 336, in _project_polygon
        return self._rings_to_multi_polygon(rings, is_ccw)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/cartopy/crs.py", line 580, in _rings_to_multi_polygon
        polygon = boundary_poly.intersection(polygon)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/shapely/geometry/base.py", line 620, in intersection
        return geom_factory(self.impl['intersection'](self, other))
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/shapely/topology.py", line 70, in __call__
        self._check_topology(err, this, other)
      File "/Users/lkilcher/anaconda3/envs/wave_res/lib/python2.7/site-packages/shapely/topology.py", line 38, in _check_topology
        self.fn.__name__, repr(geom)))
    TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0xb22f65e10>
</details>

System Info
----
OSX 10.12.6
Python 2.7.15
MPL 2.2.3
Cartopy 0.16.0
Shapely 1.6.4

<details><summary>Full System Info</summary>

Conda List
------

    appnope                   0.1.0            py27hb466136_0    anaconda
    asn1crypto                0.24.0                   py27_0  
    backports                 1.0                      py27_1    anaconda
    backports.functools_lru_cache 1.5                      py27_1    anaconda
    backports.shutil_get_terminal_size 1.0.0                    py27_2    anaconda
    backports_abc             0.5              py27h6972548_0    anaconda
    blas                      1.0                         mkl    anaconda
    bzip2                     1.0.6                h1de35cc_5    anaconda
    ca-certificates           2018.03.07                    0  
    cartopy                   0.16.0           py27h9263bd1_0  
    certifi                   2018.10.15               py27_0  
    cffi                      1.11.5           py27h6174b99_1  
    cftime                    1.0.0b1          py27h1d22016_0    anaconda
    chardet                   3.0.4                    py27_1  
    cryptography              2.3.1            py27ha12b0ac_2  
    curl                      7.62.0               ha441bb4_0  
    cycler                    0.10.0           py27hfc73c78_0    anaconda
    decorator                 4.3.0                    py27_0    anaconda
    enum34                    1.1.6                    py27_1    anaconda
    freetype                  2.9.1                hb4e5f40_0    anaconda
    functools32               3.2.3.2                  py27_1    anaconda
    futures                   3.2.0                    py27_0    anaconda
    geos                      3.6.2                h5470d99_2  
    get_terminal_size         1.0.0                h7520d66_0    anaconda
    h5py                      2.8.0            py27h878fce3_3    anaconda
    hdf4                      4.2.13               h39711bb_2    anaconda
    hdf5                      1.10.2               hfa1e0ec_1    anaconda
    icu                       58.2                 h4b95b61_1  
    idna                      2.7                      py27_0  
    intel-openmp              2018.0.3                      0    anaconda
    ipaddress                 1.0.22                   py27_0  
    ipython                   4.2.0                    py27_1    anaconda
    ipython_genutils          0.2.0            py27h8b9a179_0    anaconda
    jpeg                      9b                   he5867d9_2    anaconda
    kiwisolver                1.0.1            py27h0a44026_0    anaconda
    libcurl                   7.62.0               h051b688_0  
    libcxx                    4.0.1                h579ed51_0    anaconda
    libcxxabi                 4.0.1                hebd6815_0    anaconda
    libedit                   3.1.20170329         hb402a30_2    anaconda
    libffi                    3.2.1                h475c297_4    anaconda
    libgfortran               3.0.1                h93005f0_2    anaconda
    libiconv                  1.15                 hdd342a3_7  
    libnetcdf                 4.6.1                h148f0bd_0    anaconda
    libpng                    1.6.34               he12f830_0    anaconda
    libssh2                   1.8.0                ha12b0ac_4  
    libtiff                   4.0.9                hcb84e12_2  
    libxml2                   2.9.8                hab757c2_1  
    libxslt                   1.1.32               hb819dd2_0  
    linecache2                1.0.0                    py27_0    anaconda
    lxml                      4.2.5            py27hef8c89e_0  
    matplotlib                2.2.3            py27h54f8f79_0    anaconda
    mkl                       2018.0.3                      1    anaconda
    mkl_fft                   1.0.4            py27h5d10147_1    anaconda
    mkl_random                1.0.1            py27h5d10147_1    anaconda
    ncurses                   6.1                  h0a44026_0    anaconda
    netcdf4                   1.4.2            py27h08833f9_0    anaconda
    numpy                     1.15.3           py27h6a91979_0    anaconda
    numpy-base                1.15.3           py27h8a80b8c_0    anaconda
    olefile                   0.46                     py27_0  
    openssl                   1.1.1a               h1de35cc_0  
    owslib                    0.16.0                   py27_0  
    pandas                    0.23.4           py27h6440ff4_0  
    pathlib2                  2.3.2                    py27_0    anaconda
    pexpect                   4.6.0                    py27_0    anaconda
    pickleshare               0.7.4            py27h37e3d41_0    anaconda
    pillow                    5.2.0            py27hb68e598_0  
    pip                       18.1                     py27_0    anaconda
    proj4                     5.0.1                h1de35cc_0  
    ptyprocess                0.6.0                    py27_0    anaconda
    pycparser                 2.19                     py27_0  
    pyDictH5                  0.2.1                     <pip>
    pyepsg                    0.3.2                    py27_0  
    pyopenssl                 18.0.0                   py27_0  
    pyparsing                 2.2.0                    py27_1    anaconda
    pyproj                    1.9.5.1          py27h833a5d7_1  
    pyshp                     1.2.12                   py27_0  
    pysocks                   1.6.8                    py27_0  
    python                    2.7.15               h8f8e585_4  
    python-dateutil           2.7.3                    py27_0    anaconda
    python.app                2                        py27_8    anaconda
    pytz                      2018.5                   py27_0    anaconda
    readline                  7.0                  h1de35cc_5    anaconda
    requests                  2.19.1                   py27_0  
    scandir                   1.9.0            py27h1de35cc_0    anaconda
    scipy                     1.1.0            py27h28f7352_1    anaconda
    setuptools                40.0.0                   py27_0    anaconda
    shapely                   1.6.4            py27h20de77a_0    anaconda
    simplegeneric             0.8.1                    py27_2    anaconda
    singledispatch            3.4.0.3          py27he22c18d_0    anaconda
    six                       1.11.0                   py27_1    anaconda
    sqlite                    3.25.2               ha441bb4_0    anaconda
    subprocess32              3.5.2            py27h1de35cc_0    anaconda
    tk                        8.6.8                ha441bb4_0    anaconda
    tornado                   5.1              py27h1de35cc_0    anaconda
    tqdm                      4.28.1           py27h28b3542_0    anaconda
    traceback2                1.4.0                    py27_0    anaconda
    traitlets                 4.3.2            py27hcf08151_0    anaconda
    unittest2                 1.1.0                    py27_0    anaconda
    urllib3                   1.23                     py27_0  
    wheel                     0.31.1                   py27_0    anaconda
    xz                        5.2.4                h1de35cc_4  
    zlib                      1.2.11               hf3cbc9b_2    anaconda

</details>

</details>

**Comment by pelson** [comment]
Could you update your version of cartopy to v0.17. The code provided works for me, and cartopy v0.16 does not support proj4 v5. Hopefully that will fix the issue.

**Comment by lkilcher** [comment]
This works for me in v0.17. Thanks for all your hard work!

**Comment by pelson** [comment]
Good stuff. Thanks for following up and providing all of that useful information to make it easy to diagnose / make suggestions.

**Comment by BAFurtado** [comment]
Funny. Got the same mistake (with a shape that worked before), but the thing is, I didn't have cartopy installed. Just shapely. Trying to install cartopy...

**Comment by QuLogic** [comment]
That will not help anything. GEOS is used by many other libraries. Any error in it when you aren't using Cartopy will not be fixed by installing Cartopy.

**Comment by BAFurtado** [comment]
> That will not help anything. GEOS is used by many other libraries. Any error in it when you aren't using Cartopy will not be fixed by installing Cartopy.

Indeed. Thanks. I fixed the self intersection of the shape. What bugged me was that the shape worked fine a number ofntimes before.

**Comment by vsasseville** [comment]
> > That will not help anything. GEOS is used by many other libraries. Any error in it when you aren't using Cartopy will not be fixed by installing Cartopy.
> 
> Indeed. Thanks. I fixed the self intersection of the shape. What bugged me was that the shape worked fine a number ofntimes before.

I got the same issue, with a shape that worked before too. How did you fix it?

**Comment by BAFurtado** [comment]
I had to fix the shape itself. What I think happened is that some threshold
in the code changed and fine shapes earlier now need to be tweaked. Notice
the message, find the shape, find the polygon with a problem and fix it.
Best,

**Comment by vsasseville** [comment]
Thanks, I got the thing fixed by adding a small buffer to my shape.
