### ISSUE TITLE
Broken in Ubuntu 18.10

### ISSUE THREAD

**Issue by Tecktron** [SciTools/cartopy#1295]
### Description
I recently upgraded to  Ubuntu 18.10 and it seems that Cartopy is now broken (this was all previously working on 18.04). I checked the apt installs I'm still up to date and neither my previous virtual environment or a newly built one, worked.

Here's what I did and what I get:
`$ sudo apt-get install libproj-dev proj-data proj-bin libgeos-dev`
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgeos-dev is already the newest version (3.6.2-1build2).
libproj-dev is already the newest version (5.1.0-2).
proj-bin is already the newest version (5.1.0-2).
proj-data is already the newest version (5.1.0-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
`$ virtualenv venv`
```
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/user/cartopy-test//venv/bin/python2
Also creating executable in /home/user/cartopy-test//venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
```
`$ source ./venv/bin/activate`
`(venv)$ pip install cartopy`
```
Collecting cartopy
Collecting shapely>=1.5.6 (from cartopy)
  Using cached https://files.pythonhosted.org/packages/81/d1/b8e1b089a8ddd6df74be583d70373eac55c725c6197c115efbd3c3e1509f/Shapely-1.6.4.post2-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: setuptools>=0.7.2 in ./venv/lib/python2.7/site-packages (from cartopy) (41.0.0)
Collecting pyshp>=1.1.4 (from cartopy)
Collecting numpy>=1.10 (from cartopy)
  Using cached https://files.pythonhosted.org/packages/c4/33/8ec8dcdb4ede5d453047bbdbd01916dbaccdb63e98bba60989718f5f0876/numpy-1.16.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting six>=1.3.0 (from cartopy)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: shapely, pyshp, numpy, six, cartopy
Successfully installed cartopy-0.17.0 numpy-1.16.2 pyshp-2.1.0 shapely-1.6.4.post2 six-1.12.0
```
`(venv)$ python`
```
Python 2.7.15+ (default, Oct  2 2018, 22:12:08) 
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/cartopy-test/venv/local/lib/python2.7/site-packages/cartopy/__init__.py", line 107, in <module>
    import cartopy.crs
  File "/home/user/cartopy-test/venv/local/lib/python2.7/site-packages/cartopy/crs.py", line 36, in <module>
    from cartopy._crs import CRS, Geodetic, Globe, PROJ4_VERSION
ImportError: libproj.so.12: cannot open shared object file: No such file or directory
```

What am I missing? How do I get this working again? Thanks

**Comment by Tecktron** [comment]
Never mind, was a pip cache issue. reinstalled with --no-cache and it works now.
