### ISSUE TITLE
Error while downloading rivers_lake_centerlines 50m with feature_download.py

### ISSUE THREAD

**Issue by xylar** [SciTools/cartopy#1464]
### Description

I am using the tool `feature_download.py` to download features.  When the script reaches `rivers_lake_centerlines` at `50m` resolution, I see an error as below.

Note: I added a print statement before the error to determine which feature was the issue:
``` python
...
                        print('Feature {}, {}, {}'
                              ''.format(category, name, scale))
                        geoms = list(feature.geometries())
...
```

#### Code to reproduce

```
wget https://raw.githubusercontent.com/SciTools/cartopy/v0.18.0b1/tools/feature_download.py
mkdir cartopy_data
python feature_download.py --outputcartopy_data cultural-extra cultural gshhs physical --ignore-repo-data
```

#### Traceback 

```
...
Feature physical, rivers_lake_centerlines, 110m length: 13
Traceback (most recent call last):
  File "feature_download.py", line 137, in <module>
    download_features(args.group_names, dry_run=args.dry_run)
  File "feature_download.py", line 111, in download_features
    geoms = list(feature.geometries())
  File "/home/xylar/miniconda3/envs/mpas-analysis-cartopy18/lib/python3.7/site-packages/cartopy/feature/__init__.py", line 288, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/home/xylar/miniconda3/envs/mpas-analysis-cartopy18/lib/python3.7/site-packages/cartopy/io/shapereader.py", line 166, in geometries
    yield sgeom.shape(self._reader.shape(i))
  File "/home/xylar/miniconda3/envs/mpas-analysis-cartopy18/lib/python3.7/site-packages/shapely/geometry/geo.py", line 25, in shape
    if hasattr(context, "__geo_interface__"):
  File "/home/xylar/miniconda3/envs/mpas-analysis-cartopy18/lib/python3.7/site-packages/shapefile.py", line 262, in __geo_interface__
    raise Exception('Shape type "%s" cannot be represented as GeoJSON.' % SHAPETYPE_LOOKUP[self.shapeType])
Exception: Shape type "NULL" cannot be represented as GeoJSON.
```

<details>
 <summary>Full environment definition</summary>

### Operating system
Ubuntu 18.04.4

### Cartopy version
0.18.0b1 built locally using the conda-forge recipe, see https://github.com/conda-forge/cartopy-feedstock/pull/76

### conda list

```
# packages in environment at /home/xylar/miniconda3/envs/mpas-analysis-cartopy18:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
attrs                     19.3.0                     py_0    conda-forge
bokeh                     1.4.0                    py37_0    conda-forge
bottleneck                1.3.1            py37hc1659b7_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cartopy                   0.18.0b1         py37h88e1628_0    local
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
cftime                    1.0.4.2          py37hc1659b7_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
cmocean                   2.0                        py_3    conda-forge
colorspacious             1.1.2              pyh24bf2e0_0    conda-forge
cryptography              2.8              py37h72c5cf5_1    conda-forge
curl                      7.68.0               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask                      2.10.1                     py_0    conda-forge
dask-core                 2.10.1                     py_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
distributed               2.10.0                     py_0    conda-forge
esmf                      8.0.0           mpi_mpich_h06e08bd_105    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
geometric_features        0.1.4                      py_0    conda-forge
geos                      3.8.0                he1b5a44_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3          py37h6f030ca_1002    conda-forge
gsl                       2.6                  h294904e_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_1    conda-forge
gstreamer                 1.14.5               h36ae1b5_1    conda-forge
gsw                       3.3.1            py37hc1659b7_1    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          mpi_mpich_ha7d0aea_1004    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
importlib_metadata        1.5.0                    py37_0    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.68.0               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm9                  9.0.1                hc9558a2_0    conda-forge
libnetcdf                 4.7.3           mpi_mpich_h755db7c_1    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libxslt                   1.1.33               h31b3aaa_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.5.0            py37h7ec2d77_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
matplotlib                3.1.3                    py37_0    conda-forge
matplotlib-base           3.1.3            py37h250f245_0    conda-forge
more-itertools            8.2.0                      py_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.0.3            py37hcf07815_0    conda-forge
mpich                     3.3.2                hc856adb_0    conda-forge
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
nco                       4.9.1           mpi_mpich_h791c819_101    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf-fortran            4.5.2           mpi_mpich_hd560429_3    conda-forge
netcdf4                   1.5.3           mpi_mpich_py37h00fb2e7_2    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numpy                     1.18.1           py37h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
owslib                    0.19.1                     py_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.1            py37hb3f55d8_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pillow                    7.0.0            py37hefe7db6_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
progressbar2              3.47.0                     py_0    conda-forge
proj                      6.3.0                hc80f0dc_0    conda-forge
psutil                    5.6.7            py37h516909a_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
py                        1.8.1                      py_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pykdtree                  1.3.1           py37hc1659b7_1002    conda-forge
pyopenssl                 19.1.0                   py37_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyproj                    2.4.2.post1      py37h8ff28aa_1    conda-forge
pyqt                      5.12.3           py37hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyremap                   0.0.3                    py37_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
pytest                    5.3.5                    py37_1    conda-forge
pytest-runner             5.2                        py_0    conda-forge
python                    3.7.6                h357f687_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-utils              2.3.0                      py_1    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3              py37h516909a_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
scipy                     1.4.1            py37h921218d_0    conda-forge
setuptools                45.2.0                   py37_0    conda-forge
shapely                   1.7.0            py37h5d51c17_0    conda-forge
six                       1.14.0                   py37_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
tempest-remap             2.0.3           mpi_mpich_h21555f6_7    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_3    conda-forge
udunits2                  2.2.27.6          h4e0c4b3_1001    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xarray                    0.15.0                     py_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zict                      1.0.0                      py_0    conda-forge
zipp                      2.2.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge
```

### pip list

```
```

</details>

**Comment by greglucas** [comment]
@xylar I think this was related to #1411 which is now in master. I just made a new conda environment to test this out on master and the download works for me locally.

```bash
~/miniconda3/envs/test_cartopy_master/lib/python3.7/site-packages/cartopy/io/__init__.py:260: DownloadWarning: Downloading: https://naciscdn.org/naturalearth/50m/physical/ne_50m_rivers_lake_centerlines.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)
Feature physical, rivers_lake_centerlines, 50m length: 461
```

I'm going to close for now. Please reopen if you are still running into issues.
