### ISSUE TITLE
GSHHS Feature not downloadable... 

### ISSUE THREAD

**Issue by toby2399** [SciTools/cartopy#1502]
### Description
When trying to create a map using cartopy feature GSHHS I get a resource not found error.  No matter what level of detail I specify I get the same error. I checked the downloaded file and the file is there, but for some reason software cannot find it. 

#### Code to reproduce

```
map_ax.add_feature(cfeature.GSHHSFeature('high', levels=[1, 2], edgecolor='black'))
```

#### Traceback 
```
C:\ProgramData\Anaconda3\lib\site-packages\cartopy\io\__init__.py:260: DownloadWarning: Downloading: https://www.ngdc.noaa.gov/mgg/shorelines/data/gshhs/oldversions/version2.2.0/GSHHS_shp_2.2.0.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)
Traceback (most recent call last):
  File "c:\Users\Toby Peele\.vscode\extensions\ms-python.python-2019.8.30787\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\Toby Peele\.vscode\extensions\ms-python.python-2019.8.30787\pythonFiles\lib\python\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\Toby Peele\.vscode\extensions\ms-python.python-2019.8.30787\pythonFiles\lib\python\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Toby Peele\OneDrive - North Carolina State University\Python\sensor_plot\sensor_plot.py", line 424, in <module>
    main(sys.argv[1:])
  File "c:\Users\Toby Peele\OneDrive - North Carolina State University\Python\sensor_plot\sensor_plot.py", line 285, in main
    fig.canvas.draw()
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cartopy\mpl\geoaxes.py", line 385, in draw
    inframe=inframe)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cartopy\mpl\feature_artist.py", line 142, in draw
    for geom in geoms:
  File "C:\ProgramData\Anaconda3\lib\site-packages\cartopy\feature.py", line 312, in intersecting_geometries
    path = shapereader.gshhs(scale, level)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cartopy\io\shapereader.py", line 379, in gshhs
    return gshhs_downloader.path(format_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cartopy\io\__init__.py", line 222, in path
    result_path = self.acquire_resource(target_path, format_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cartopy\io\shapereader.py", line 466, in acquire_resource
    self.acquire_all_resources(format_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cartopy\io\shapereader.py", line 440, in acquire_all_resources
    member = zfh.getinfo(member_path)
  File "C:\ProgramData\Anaconda3\lib\zipfile.py", line 1431, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'GSHHS_shp\\\\c\\\\GSHHS_c_L1.shp' in the archive"
```
<details>
 <summary>Full environment definition</summary>

### Operating system
Windows 10

### Cartopy version
Cartopy 0.16
</details>

**Comment by QuLogic** [comment]
I believe this was fixed by https://github.com/SciTools/cartopy/pull/1083; please update to a newer version.
