### ISSUE TITLE
New M1 Chip Macbook errors

### ISSUE THREAD

**Issue by WangYuuuuuu** [SciTools/cartopy#1687]
### Description
I'm now using the new M1 chip macbook for python. After I installed the cartopy sucessfully, however, there is an error when I import the cartopy.

Here are the Traceback from Python

#### Code to reproduce

import cartopy

#### Traceback 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yuu/anaconda3/lib/python3.7/site-packages/cartopy/__init__.py", line 107, in <module>
    import cartopy.crs
  File "/Users/yuu/anaconda3/lib/python3.7/site-packages/cartopy/crs.py", line 32, in <module>
    import shapely.geometry as sgeom
  File "/Users/yuu/anaconda3/lib/python3.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/Users/yuu/anaconda3/lib/python3.7/site-packages/shapely/geometry/base.py", line 17, in <module>
    from shapely.coords import CoordinateSequence
  File "/Users/yuu/anaconda3/lib/python3.7/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/Users/yuu/anaconda3/lib/python3.7/site-packages/shapely/geos.py", line 113, in <module>
    free = load_dll('c').free
  File "/Users/yuu/anaconda3/lib/python3.7/site-packages/shapely/geos.py", line 56, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib c or load any of its variants [].

### Operating system

M1 chip macbook air with Big Sur

### Cartopy version

Cartopy(0.17.0)

**Comment by dopplershift** [comment]
Based on that traceback, the error is coming out of Shapely:
```
File "/Users/yuu/anaconda3/lib/python3.7/site-packages/shapely/geos.py", line 113, in 
free = load_dll('c').free
File "/Users/yuu/anaconda3/lib/python3.7/site-packages/shapely/geos.py", line 56, in load_dll
libname, fallbacks or []))
OSError: Could not find lib c or load any of its variants [].
```

So probably best to raise this on [their github(https://github.com/Toblerity/Shapely). There's nothing we can do about it here.

**Comment by ocefpaf** [comment]
> So probably best to raise this on [their github(https://github.com/Toblerity/Shapely). There's nothing we can do about it here.

Looks like you are using the Rosetta emulation. In that case I would not open issues upstream b/c they will probably be clueless on how to help you. If Apple has a forum or something to collect those failures you should report them there.

Also, conda-forge has a few native OSX-ARM64 builds, but not cartopy yet. (@dopplershift is that something you would like to try to do? If so ping me and I can connect you to the people building this architecture.)

**Comment by dopplershift** [comment]
@ocefpaf I'd be willing to take a look. I kinda figured it was an automated thing and eventually a PR from the bots would show up trying to enable it at the [feedstock](https://github.com/conda-forge/cartopy-feedstock).

**Comment by ocefpaf** [comment]
> @ocefpaf I'd be willing to take a look. I kinda figured it was an automated thing and eventually a PR from the bots would show up trying to enable it at the [feedstock](https://github.com/conda-forge/cartopy-feedstock).

Yes and no. We are curating a [list for the bot](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt), so we need to add cartopy there. The bot will navigate the tree all the way up to cartopy but there are changes that things may be broken along the way, like `proj`, then we need to fix the build so the bot can proceed.
