### ISSUE TITLE
Python 3.8 Compatibility

### ISSUE THREAD

**Issue by Guymer** [SciTools/cartopy#1776]
### Description

I run FreeBSD and install Cartopy using the ports system. Yesterday I moved from Python 3.7 to Python 3.8 and I reinstalled all of my Python packages too. One of my overnight scripts no longer works as, I presume, a list method has been removed.

#### Traceback

```none
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/cartopy/io/shapereader.py", line 168, in records
    attributes = shape_record.record.as_dict()
AttributeError: 'list' object has no attribute 'as_dict'
```

#### Code to reproduce

```python
import cartopy
sfile = cartopy.io.shapereader.natural_earth(
    resolution = "10m",
    category = "cultural",
    name = "admin_0_countries",
)
for record in cartopy.io.shapereader.Reader(sfile).records():
    print(record.attributes["NAME"])
``` 

### Operating system

```none
> uname -a
FreeBSD example.com 12.2-RELEASE-p6 FreeBSD 12.2-RELEASE-p6 GENERIC  amd64
```

### Cartopy version

* Python 3.8.9
* Cartopy 0.19.0.post1

### pip list

```none
> pip-3.8 list
Package                       Version
----------------------------- ------------
alabaster                     0.7.6
astroid                       2.5.4
awscli                        1.19.61
Babel                         2.9.0
Beaker                        1.11.0
beautifulsoup4                4.9.3
boto3                         1.17.61
botocore                      1.20.61
Cartopy                       0.19.0.post1
certifi                       2020.12.5
cffi                          1.14.5
chardet                       3.0.4
colorama                      0.4.4
cryptography                  3.3.2
cycler                        0.10.0
Cython                        0.29.21
dnspython                     1.16.0
docutils                      0.17.1
ephem                         3.7.7.1
ExifRead                      2.1.2
file-magic                    0.4.0
GDAL                          3.2.2
geojson                       2.3.0
html5lib                      1.0.1
idna                          2.10
imagesize                     1.1.0
isort                         5.8.0
Jinja2                        2.11.2
jmespath                      0.10.0
kiwisolver                    1.1.0
lazy-object-proxy             1.6.0
lensfun                       0.3.95
libxml2-python                2.9.10
lxml                          4.6.3
Mako                          1.0.14
Markdown                      2.6.11
MarkupSafe                    1.1.1
matplotlib                    3.3.3
mccabe                        0.6.1
meson                         0.57.1
nose                          1.3.7
numpy                         1.16.6
olefile                       0.46
packaging                     20.9
Pillow                        7.0.0
pip                           20.3.4
pluggy                        0.13.1
pyasn1                        0.4.7
pybind11                      2.6.2
pycparser                     2.20
Pygments                      2.7.2
pylint                        2.8.0
pyOpenSSL                     20.0.1
pyparsing                     2.4.7
pyRFC3339                     1.1
pyshp                         1.2.12
PySocks                       1.7.1
PyStemmer                     2.0.0.1
python-dateutil               2.8.1
python-gist                   0.10.3
python-gnupg                  0.4.5
pytz                          2020.5
PyYAML                        5.3.1
requests                      2.22.0
rsa                           3.4.2
s3transfer                    0.4.2
scipy                         1.6.0
setuptools                    44.0.0
setuptools-scm                4.1.2
Shapely                       1.7.1
simplejson                    3.17.2
six                           1.15.0
snowballstemmer               1.2.1
soupsieve                     2.0.1
Sphinx                        3.5.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
sysctl                        0.3.2
Tkinter                       0.0.0
toml                          0.10.2
tornado                       6.1
urllib3                       1.25.11
webencodings                  0.5.1
wrapt                         1.12.1
```

**Comment by Guymer** [comment]
Curiously, the exact same code works fine on MacOS (when using Cartopy 0.18.0 rather than 0.19.0.post1).

```none
> uname -a
Darwin example.com 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:14 PST 2021; root:xnu-7195.101.1~3/RELEASE_X86_64 x86_64
```

```none
> python3.8 --version
Python 3.8.9
```

```none
> pip list 
Package                       Version
----------------------------- ---------
alabaster                     0.7.12
astroid                       2.5.3
attrs                         20.3.0
awscli                        1.19.58
Babel                         2.9.0
boto3                         1.17.12
botocore                      1.20.58
Cartopy                       0.18.0
certifi                       2020.12.5
chardet                       4.0.0
colorama                      0.4.4
convertbng                    0.6.25
cycler                        0.10.0
Cython                        0.29.23
docopt                        0.6.2
docutils                      0.17.1
ephem                         3.7.7.0
ExifRead                      2.3.1
filelock                      3.0.12
GDAL                          3.2.1
geojson                       2.5.0
idna                          3.1
imagesize                     1.2.0
iniconfig                     1.1.1
ipaddress                     1.0.23
isort                         5.8.0
Jinja2                        2.11.3
jmespath                      0.10.0
kiwisolver                    1.3.1
lazy-object-proxy             1.5.2
lxml                          4.4.1
MarkupSafe                    1.1.1
matplotlib                    3.4.1
mccabe                        0.6.1
mock                          4.0.3
mypy                          0.812
mypy-extensions               0.4.3
nose                          1.3.7
numpy                         1.20.2
olefile                       0.46
OWSLib                        0.19.0
packaging                     20.9
Pillow                        8.2.0
pip                           21.1
pluggy                        0.13.1
py                            1.10.0
pyasn1                        0.4.8
pybind11                      2.6.2
pycairo                       1.20.0
pycrypto                      2.6.1
pyepsg                        0.4.0
Pygments                      2.8.1
pylint                        2.7.2
pyparsing                     2.4.7
pyproj                        3.0.1
pyRFC3339                     1.1
pyshp                         2.1.3
pytest                        6.2.3
pytest-runner                 5.2
python-dateutil               2.8.1
python-gist                   0.9.2
python-gnupg                  0.4.6
pytz                          2021.1
PyYAML                        5.4.1
requests                      2.25.1
roman                         3.3
rsa                           4.6
s3transfer                    0.3.4
scipy                         1.6.3
setuptools                    54.2.0
Shapely                       1.7.1
simplejson                    3.17.2
six                           1.15.0
snowballstemmer               2.1.0
Sphinx                        3.5.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
tkinter                       0.0.0
toml                          0.10.2
tornado                       6.1
typed-ast                     1.4.3
typing-extensions             3.7.4.3
urllib3                       1.26.4
wheel                         0.36.2
wrapt                         1.12.1
youtube-dl                    2021.4.17
```

**Comment by greglucas** [comment]
The dependency on pyshp is >= 2.
https://github.com/SciTools/cartopy/blob/32b203b526475c942806f4b8485414f72fb49f98/requirements/default.txt#L3

Were you installing via pip?

**Comment by Guymer** [comment]
Hi,

I have been installing it via `portmaster` on FreeBSD (which uses the port tree). The Portfile for Cartopy only has a  dependency of `>=1.1.4`, see  https://github.com/freebsd/freebsd-ports/blob/main/graphics/py-cartopy/Makefile#L24. Furthermore, it appears that `1.2.12` is the latest version in the port tree, see https://github.com/freebsd/freebsd-ports/blob/main/devel/py-pyshp/Makefile#L2. I will raise a ticket to get those fixed and then try the above minimum working example again.

Thank you

**Comment by Guymer** [comment]
FYI, I have raised the following ticket on the FreeBSD port of Cartopy here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255622

**Comment by greglucas** [comment]
Unfortunately, I don't think there is anything we can do on our end. I'm going to close this for now, feel free to reopen if there is an action for us to update our requirements file or anything like that.

**Comment by Guymer** [comment]
> The dependency on pyshp is >= 2.
> 
> https://github.com/SciTools/cartopy/blob/32b203b526475c942806f4b8485414f72fb49f98/requirements/default.txt#L3
> 
> Were you installing via pip?

You were right; after "pyshp" got updated in the FreeBSD port tree Cartopy now works fine - thanks!
