### ISSUE TITLE
Broken "Web services" examples in the latest (currently v 0.19) gallery page

### ISSUE THREAD

**Issue by jypeter** [SciTools/cartopy#1777]
- [v 0.18](https://scitools.org.uk/cartopy/docs/v0.18/gallery/#web-services) looks good !
- [v 0.19 aka _latest_](https://scitools.org.uk/cartopy/docs/latest/gallery/#web-services) shows _broken_ images and the examples that should produce the images seem to have the same traceback
```
Traceback (most recent call last):
  File "/root/project/examples/web_services/reprojected_wmts.py", line 54, in <module>
    plot_city_lights()
  File "/root/project/examples/web_services/reprojected_wmts.py", line 40, in plot_city_lights
    ax.add_wmts(base_uri, layer_name=layer_name)
  File "/root/project/lib/cartopy/mpl/geoaxes.py", line 2140, in add_wmts
    gettile_extra_kwargs=wmts_kwargs)
  File "/root/project/lib/cartopy/io/ogc_clients.py", line 356, in __init__
    wmts = owslib.wmts.WebMapTileService(wmts)
  File "/opt/conda/envs/test-environment/lib/python3.7/site-packages/owslib/wmts.py", line 189, in __init__
    self._buildMetadata(parse_remote_metadata)
  File "/opt/conda/envs/test-environment/lib/python3.7/site-packages/owslib/wmts.py", line 240, in _buildMetadata
    gather_layers(caps, None)
  File "/opt/conda/envs/test-environment/lib/python3.7/site-packages/owslib/wmts.py", line 237, in gather_layers
    'already exists' % cm.id)
KeyError: 'Content metadata for layer "AMSUA_NOAA15_Brightness_Temp_Channel_10" already exists'
```

**Comment by greglucas** [comment]
Yes, they were broken upstream when we released.
https://github.com/SciTools/cartopy/pull/1703#issuecomment-824081944

These seem to fail on/off at various times out of our control, so I'm not super inclined to update those examples either...

**Comment by jypeter** [comment]
Oh, OK! Well, as long as there is still a placeholder in the gallery for these examples, people can always have a look at the expected result by looking at the previous version.

I will have to remember the convenient _version selector_ pull-down menu at the top right of the documentation !

**Comment by greglucas** [comment]
Yeah, it is unfortunate that happened to us. I'm going to close this as "won't fix" just because it is playing whack-a-mole with WMTS.
