### ISSUE TITLE
Contourf Not Working When Used in For Loop

### ISSUE THREAD

**Issue by michaelavs** [SciTools/cartopy#1855]
### Description

Currently trying to make a gif using Matplotlib Animate of rain data during a flood event. I can plot individual time steps by calling each index value, but when using the same contourf function in a for loop to generate the plots for the gif, I get the following error:
```ValueError: Axes should be an instance of GeoAxes, got <class 'matplotlib.axes._subplots.AxesSubplot'>```

And then a subsequent error of:
```
IndexError: list index out of range
```
I receive the ValueError anytime I attempt to use a for loop to generate multiple plots, but I get ValueError and IndexError when trying to generate plots and then use mpl Animate. The code is able to produce the first plot in the series (index 0), but stops/errors after that. 

#### Code to reproduce
Individual plot code (works)
```
ds = xr.open_dataset("*/daymet_v3_prcp_2013_na.nc4")
prcp = ds.prcp[251:259]

fig = plt.figure(figsize=(15,15))
proj = ccrs.PlateCarree()
ax = plt.axes(projection=proj)
ax.coastlines()
ax.add_feature(cfeature.LAND)
ax.add_feature(cfeature.NaturalEarthFeature(category='cultural',
                             name='admin_1_states_provinces_shp',
                             scale='50m',
                             facecolor='none',
                             edgecolor='black',
                             ))

plt.contourf(prcp[0].lon,
                 prcp[0].lat,
                 prcp[0],
                 transform=proj,
                 levels=np.arange(0,55,2))
plt.show()
```
Using for loop to go through each time step (excluding code that is repeated in first snippet):
```
def plot_map(indx):
    plt.contourf(prcp[indx].lon,
                 prcp[indx].lat,
                 prcp[indx],
                 transform=proj,
                 levels=np.arange(0,55,2))
    plt.tight_layout()
    plt.savefig("prcp_"+str(indx)+".png")
    plt.show()

for i in range(len(prcp)):
    plot_map(i)
```
Code used with mpl Animate (excluding code that is repeated in first snippet):
```
def animate(i):
    plt.contourf(prcp[i].lon,
                 prcp[i].lat,
                 prcp[i],
                 transform=proj,
                 levels=np.arange(0,55,2))
    plt.tight_layout()
    plt.show()

anim = animation.FuncAnimation(fig, animate,)

anim.save('test_ani.gif',  )

```
#### Traceback 
For loop only:
```
Traceback (most recent call last):
  File "/Users/misi1684/pythia-foundations/page_art.py", line 61, in <module>
    plot_map(i)
  File "/Users/misi1684/pythia-foundations/page_art.py", line 51, in plot_map
    plt.contourf(prcp[indx].lon,
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2745, in contourf
    __ret = gca().contourf(
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/__init__.py", line 1361, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 6434, in contourf
    contours = mcontour.QuadContourSet(self, *args, **kwargs)
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/contour.py", line 777, in __init__
    kwargs = self._process_args(*args, **kwargs)
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/contour.py", line 1375, in _process_args
    t = self.get_transform()
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/contour.py", line 895, in get_transform
    self._transform = self._transform._as_mpl_transform(self.axes)
  File "lib/cartopy/_crs.pyx", line 308, in cartopy._crs.CRS._as_mpl_transform
ValueError: Axes should be an instance of GeoAxes, got <class 'matplotlib.axes._subplots.AxesSubplot'>
```
For loop and mpl Animate:
```
Traceback (most recent call last):
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/animation.py", line 236, in saving
    yield self
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/animation.py", line 1173, in save
    anim._draw_next_frame(d, blit=False)
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/animation.py", line 1208, in _draw_next_frame
    self._draw_frame(framedata)
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/animation.py", line 1776, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "/Users/misi1684/pythia-foundations/page_art.py", line 51, in animate
    plt.contourf(prcp[i].lon,
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2745, in contourf
    __ret = gca().contourf(
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/__init__.py", line 1361, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 6434, in contourf
    contours = mcontour.QuadContourSet(self, *args, **kwargs)
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/contour.py", line 777, in __init__
    kwargs = self._process_args(*args, **kwargs)
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/contour.py", line 1375, in _process_args
    t = self.get_transform()
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/contour.py", line 895, in get_transform
    self._transform = self._transform._as_mpl_transform(self.axes)
  File "lib/cartopy/_crs.pyx", line 308, in cartopy._crs.CRS._as_mpl_transform
ValueError: Axes should be an instance of GeoAxes, got <class 'matplotlib.axes._subplots.AxesSubplot'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/misi1684/pythia-foundations/page_art.py", line 69, in <module>
    anim.save('test_ani.gif',  )
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/animation.py", line 1177, in save
    writer.grab_frame(**savefig_kwargs)
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/animation.py", line 238, in saving
    self.finish()
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/animation.py", line 540, in finish
    self._frames[0].save(
IndexError: list index out of range
```
<details>
 <summary>Full environment definition</summary>

### Operating system

MacOS BigSur 11.5.2
### conda list

```
cartopy                   0.18.0
matplotlib                3.4.2
```

### pip list

```
```

</details>

**Comment by dopplershift** [comment]
`FuncAnimation` isn't really the right tool here. That's intended for when you can update the data underlying the plotting objects. That doesn't work for `contourf`, so you need to do like you initially do and call it in a loop; but then you need to use `ArtistAnimation`:
```python
ds = xr.open_dataset("*/daymet_v3_prcp_2013_na.nc4")
prcp = ds.prcp[251:259]

fig = plt.figure(figsize=(15, 15))
proj = ccrs.PlateCarree()
ax = plt.axes(projection=proj)
ax.coastlines()
ax.add_feature(cfeature.LAND)
ax.add_feature(cfeature.NaturalEarthFeature(category='cultural',
                             name='admin_1_states_provinces_shp',
                             scale='50m',
                             facecolor='none',
                             edgecolor='black',
                             ))

anim_artists = []
for prcp_slice in prcp:
    frame = []
    cntr = ax.contourf(prcp_slice.lon,
                 prcp[indx].lat,
                 prcp[indx],
                 transform=proj,
                 levels=np.arange(0,55,2))
    frame.append(cntr)
    anim_artists.append(frame)

plt.tight_layout()
anim = animation.ArtistAnimation(fig, anim_artists)
anim.save('test_ani.gif')
plt.show()
```

Also note the use of `ax.contourf` rather than `plt.contourf`. I think the latter is causing some of your problem, where matplotlib's global state management is getting crossed up by the loop (and maybe the repeated calls to `show()`.

**Comment by michaelavs** [comment]
Thanks for the prompt response! 
I tested the code you provided and I get almost the exact same results as before. The only difference is that instead of a ValueError, I get an AttributeError:
```
Traceback (most recent call last):
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/animation.py", line 236, in saving
    yield self
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/animation.py", line 1160, in save
    anim._init_draw()  # Clear the initial frame
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/animation.py", line 1534, in _init_draw
    artist.set_visible(False)
AttributeError: 'GeoContourSet' object has no attribute 'set_visible'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/misi1684/pythia-foundations/page_art.py", line 45, in <module>
    anim.save('test_ani.gif')
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/animation.py", line 1177, in save
    writer.grab_frame(**savefig_kwargs)
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/animation.py", line 238, in saving
    self.finish()
  File "/Users/misi1684/opt/anaconda3/envs/geocat-examples/lib/python3.8/site-packages/matplotlib/animation.py", line 540, in finish
    self._frames[0].save(
IndexError: list index out of range
```
It seems like there is an issue with how Cartopy and Matplotlib work together when plotting the data using a transform argument, but that assumption is based on the tracebacks from my original method and I can't figure out why they would suddenly stop working together. I did notice that the IndexError was also occurring for [another code](https://geocat-examples.readthedocs.io/en/latest/gallery/Animations/NCL_animate_1.html#sphx-glr-gallery-animations-ncl-animate-1-py) that used mpl animation when RTD builds it, but I haven't had the chance to re-run that code locally and see if the error continued outside of RTD (and it seems to have resolved itself overall).

**Comment by dopplershift** [comment]
I just forgot that `contour`/`contourf` are (were?) weird matplotlib functions that don't return artists, but a container that hides them in there. How about this:
```python
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from matplotlib import animation
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr

ds = xr.open_dataset("*/daymet_v3_prcp_2013_na.nc4")
prcp = ds.prcp[251:259]

fig = plt.figure(figsize=(15, 15))
proj = ccrs.PlateCarree()
ax = plt.axes(projection=proj)
ax.coastlines()
ax.add_feature(cfeature.LAND)
ax.add_feature(cfeature.STATES)

anim_artists = []
for prcp_slice in prcp:
    cntr = ax.contourf(prcp_slice.longitude, prcp_slice.latitude, prcp_slice,
                 transform=proj)
    anim_artists.append(cntr.collections)

plt.tight_layout()
anim = animation.ArtistAnimation(fig, anim_artists)
anim.save('test_ani.gif')
```

**Comment by michaelavs** [comment]
That worked, thank you! I'll also try this method on the other animation plot that wasn't building in RTD and see if I can resolve the issue there as well.
