### ISSUE TITLE
URLError in georeferenced plots

### ISSUE THREAD

**Issue by hzfywhn** [SciTools/cartopy#1873]
### Description

I recently installed cartopy on a new machine using conda. The problem comes that the same plotting script works on another machine, but not on this new one. I selected a minimum amount of codes to reproduce the problem:

#### Code to reproduce

```
from matplotlib import use
use('Agg')
from matplotlib.pyplot import figure
from cartopy.crs import PlateCarree
fig = figure()
axes = fig.add_subplot(projection=PlateCarree())
axes.coastlines()
fig.savefig(fname='fig.png')
```

#### Traceback 

```
/home/haonanw/miniconda3/lib/python3.9/site-packages/cartopy/io/__init__.py:241: DownloadWarning: Downloading: https://naciscdn.org/naturalearth/110m/physical/ne_110m_coastline.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)
Traceback (most recent call last):
  File "/home/haonanw/miniconda3/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/haonanw/miniconda3/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/haonanw/miniconda3/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/haonanw/miniconda3/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/haonanw/miniconda3/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/home/haonanw/miniconda3/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/home/haonanw/miniconda3/lib/python3.9/http/client.py", line 1415, in connect
    super().connect()
  File "/home/haonanw/miniconda3/lib/python3.9/http/client.py", line 919, in connect
    self.sock = self._create_connection(
  File "/home/haonanw/miniconda3/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/haonanw/miniconda3/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/haonanw/Downloads/cartopy_test.py", line 10, in <module>
    fig.savefig(fname='fig.png')
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/matplotlib/figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/cartopy/mpl/geoaxes.py", line 517, in draw
    return matplotlib.axes.Axes.draw(self, renderer=renderer, **kwargs)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 2747, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/cartopy/mpl/feature_artist.py", line 153, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/cartopy/feature/__init__.py", line 297, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/cartopy/feature/__init__.py", line 106, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/cartopy/feature/__init__.py", line 279, in geometries
    path = shapereader.natural_earth(resolution=self.scale,
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/cartopy/io/shapereader.py", line 282, in natural_earth
    return ne_downloader.path(format_dict)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/cartopy/io/__init__.py", line 203, in path
    result_path = self.acquire_resource(target_path, format_dict)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/cartopy/io/shapereader.py", line 337, in acquire_resource
    shapefile_online = self._urlopen(url)
  File "/home/haonanw/miniconda3/lib/python3.9/site-packages/cartopy/io/__init__.py", line 242, in _urlopen
    return urlopen(url)
  File "/home/haonanw/miniconda3/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/haonanw/miniconda3/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/home/haonanw/miniconda3/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/haonanw/miniconda3/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/haonanw/miniconda3/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/haonanw/miniconda3/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
```

<details>
 <summary>Full environment definition</summary>

### Operating system
Linux DESKTOP-6JKFP5K 4.4.0-19041-Microsoft #1151-Microsoft x86_64 GNU/Linux

### Cartopy version
0.19.0.post1

### conda list

```
# packages in environment at /home/haonanw/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
aacgmv2                   2.6.2                    pypi_0    pypi
blas                      1.0                         mkl
brotlipy                  0.7.0           py39h27cfd23_1003
c-ares                    1.17.1               h27cfd23_0
ca-certificates           2021.7.5             h06a4308_1
cartopy                   0.19.0.post1     py39h3b23250_0    conda-forge
certifi                   2021.5.30        py39h06a4308_0
cffi                      1.14.6           py39h400218f_0
cftime                    1.5.0            py39h6323ea4_0
chardet                   4.0.0           py39h06a4308_1003
conda                     4.10.3           py39h06a4308_0
conda-package-handling    1.7.3            py39h27cfd23_1
cryptography              3.4.7            py39hd23ed53_0
curl                      7.78.0               h1ccaba5_0
cycler                    0.10.0                     py_2    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
geos                      3.9.1                h9c3ff4c_2    conda-forge
hdf4                      4.2.13               h3ca952b_2
hdf5                      1.10.6               hb1b8bf9_0
idna                      2.10               pyhd3eb1b0_0
intel-openmp              2021.3.0          h06a4308_3350
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
kiwisolver                1.3.1            py39h2531618_0
krb5                      1.19.2               hcc1bbae_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               h7274673_9
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libcurl                   7.78.0               h0b77cf5_0
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.3.0               h5101ec6_17
libgfortran-ng            7.5.0               ha8ba4b0_17
libgfortran4              7.5.0               ha8ba4b0_17
libgomp                   9.3.0               h5101ec6_17
libnetcdf                 4.6.1                h2053bdc_4
libnghttp2                1.43.0               h812cca2_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.9.0                h1ba5d50_1
libstdcxx-ng              9.3.0               hd4cf53a_17
libtiff                   4.3.0                hf544144_1    conda-forge
libwebp-base              1.2.0                h27cfd23_0
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
matplotlib-base           3.3.4            py39h2fa2bec_0    conda-forge
mkl                       2021.3.0           h06a4308_520
mkl-service               2.4.0            py39h7f8727e_0
mkl_fft                   1.3.0            py39h42c9631_2
mkl_random                1.2.2            py39h51133e4_0
ncurses                   6.2                  he6710b0_1
netcdf4                   1.5.7            py39he70f4c8_0
numpy                     1.20.3           py39hf144106_0
numpy-base                1.20.3           py39h74d4b33_0
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1l               h7f8727e_0
pillow                    7.2.0            py39h6f3857e_2    conda-forge
pip                       21.1.3           py39h06a4308_0
proj                      7.2.0                h277dcde_2    conda-forge
pycosat                   0.6.3            py39h27cfd23_0
pycparser                 2.20                       py_2
pyopenssl                 20.0.1             pyhd3eb1b0_1
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyshp                     2.1.3              pyh44b312d_0    conda-forge
pysocks                   1.7.1            py39h06a4308_0
python                    3.9.5                h12debd9_4
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1                  h27cfd23_0
requests                  2.25.1             pyhd3eb1b0_0
ruamel_yaml               0.15.100         py39h27cfd23_0
scipy                     1.7.1            py39h292c36d_2
setuptools                52.0.0           py39h06a4308_0
shapely                   1.7.1            py39ha61afbd_5    conda-forge
six                       1.16.0             pyhd3eb1b0_0
sqlite                    3.36.0               hc218d9a_0
tk                        8.6.10               hbc83047_0
tornado                   6.1              py39h3811e60_1    conda-forge
tqdm                      4.61.2             pyhd3eb1b0_1
tzdata                    2021a                h52ac0ba_0
urllib3                   1.26.6             pyhd3eb1b0_1
wheel                     0.36.2             pyhd3eb1b0_0
xz                        5.2.5                h7b6447c_0
yaml                      0.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.5.0                ha95c52a_0    conda-forge
```

### pip list

```
Package                Version
---------------------- -------------------
aacgmv2                2.6.2
brotlipy               0.7.0
Cartopy                0.19.0.post1
certifi                2021.5.30
cffi                   1.14.6
cftime                 1.5.0
chardet                4.0.0
conda                  4.10.3
conda-package-handling 1.7.3
cryptography           3.4.7
cycler                 0.10.0
idna                   2.10
kiwisolver             1.3.1
matplotlib             3.3.4
mkl-fft                1.3.0
mkl-random             1.2.2
mkl-service            2.4.0
netCDF4                1.5.7
numpy                  1.20.3
olefile                0.46
Pillow                 7.2.0
pip                    21.1.3
pycosat                0.6.3
pycparser              2.20
pyOpenSSL              20.0.1
pyparsing              2.4.7
pyshp                  2.1.3
PySocks                1.7.1
python-dateutil        2.8.2
requests               2.25.1
ruamel-yaml-conda      0.15.100
scipy                  1.7.1
setuptools             52.0.0.post20210125
Shapely                1.7.1
six                    1.16.0
tornado                6.1
tqdm                   4.61.2
urllib3                1.26.6
wheel                  0.36.2
```

</details>

**Comment by akrherz** [comment]
see #1833, #1849.  Try `conda update cartopy` and see if you get a newer build of 0.19 with this problem fixed.

**Comment by hzfywhn** [comment]
Yes, the URL problem is solved after updating cartopy. It seems that the link to the map file is changed.
