### ISSUE TITLE
ImportError with Symbol not found

### ISSUE THREAD

**Issue by jajcayn** [SciTools/cartopy#1881]
### Description
Hey all, I was able to install `cartopy` using pip, seemed ok, install was without any problems.
However on
```bash
python -c "import cartopy.crs as ccrs" 
```

I am getting:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/nikola/.virtualenvs/climpy3/lib/python3.7/site-packages/cartopy/__init__.py", line 107, in <module>
    import cartopy.crs
  File "/Users/nikola/.virtualenvs/climpy3/lib/python3.7/site-packages/cartopy/crs.py", line 26, in <module>
    import cartopy.trace
ImportError: dlopen(/Users/nikola/.virtualenvs/climpy3/lib/python3.7/site-packages/cartopy/trace.cpython-37m-darwin.so, 2): Symbol not found: _GEOSCoordSeq_create_r
  Referenced from: /Users/nikola/.virtualenvs/climpy3/lib/python3.7/site-packages/cartopy/trace.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/nikola/.virtualenvs/climpy3/lib/python3.7/site-packages/cartopy/trace.cpython-37m-darwin.so
```

#### Code to reproduce
MacOS 11.6, Python 3.7.12 (x86), fresh virtualenv
```
brew install proj geos
pip install shapely --no-binary shapely
pip install cartopy
```

#### Traceback 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/nikola/.virtualenvs/climpy3/lib/python3.7/site-packages/cartopy/__init__.py", line 107, in <module>
    import cartopy.crs
  File "/Users/nikola/.virtualenvs/climpy3/lib/python3.7/site-packages/cartopy/crs.py", line 26, in <module>
    import cartopy.trace
ImportError: dlopen(/Users/nikola/.virtualenvs/climpy3/lib/python3.7/site-packages/cartopy/trace.cpython-37m-darwin.so, 2): Symbol not found: _GEOSCoordSeq_create_r
  Referenced from: /Users/nikola/.virtualenvs/climpy3/lib/python3.7/site-packages/cartopy/trace.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/nikola/.virtualenvs/climpy3/lib/python3.7/site-packages/cartopy/trace.cpython-37m-darwin.so
```

<details>
 <summary>Full environment definition</summary>

### Operating system
MacOS 11.6

### Cartopy version
0.20.0

### conda list

```
```

### pip list

```
anyio                     3.3.1
appnope                   0.1.2
argcomplete               1.12.3
argon2-cffi               21.1.0
attrs                     21.2.0
Babel                     2.9.1
backcall                  0.2.0
black                     21.9b0
bleach                    4.1.0
Cartopy                   0.20.0
certifi                   2021.5.30
cffi                      1.14.6
cftime                    1.5.0
charset-normalizer        2.0.6
click                     8.0.1
colorama                  0.4.4
cycler                    0.10.0
Cython                    0.29.24
debugpy                   1.4.3
decorator                 5.1.0
defusedxml                0.7.1
dill                      0.3.4
entrypoints               0.3
flake8                    3.9.2
gitdb                     4.0.7
GitPython                 3.1.24
idna                      3.2
importlib-metadata        4.8.1
iniconfig                 1.1.1
ipykernel                 6.4.1
ipython                   7.27.0
ipython-genutils          0.2.0
ipywidgets                7.6.5
isort                     5.9.3
jedi                      0.18.0
Jinja2                    3.0.1
joblib                    1.0.1
json5                     0.9.6
jsonschema                3.2.0
jupyter-client            7.0.3
jupyter-core              4.8.1
jupyter-server            1.11.0
jupyter-server-mathjax    0.2.3
jupyterlab                3.1.12
jupyterlab-code-formatter 1.4.10
jupyterlab-git            0.32.4
jupyterlab-pygments       0.1.2
jupyterlab-server         2.8.1
jupyterlab-sublime        0.4.1
jupyterlab-widgets        1.0.2
kiwisolver                1.3.2
MarkupSafe                2.0.1
matplotlib                3.4.3
matplotlib-inline         0.1.3
mccabe                    0.6.1
mistune                   0.8.4
multiprocess              0.70.12.2
mypy-extensions           0.4.3
nbclassic                 0.3.2
nbclient                  0.5.4
nbconvert                 6.1.0
nbdime                    3.1.0
nbformat                  5.1.3
nest-asyncio              1.5.1
netCDF4                   1.5.7
notebook                  6.4.4
numpy                     1.21.2
packaging                 21.0
pandas                    1.3.3
pandocfilters             1.5.0
parso                     0.8.2
pathos                    0.2.8
pathspec                  0.9.0
pexpect                   4.8.0
pickleshare               0.7.5
Pillow                    8.3.2
pip                       21.2.4
platformdirs              2.3.0
pluggy                    1.0.0
pox                       0.3.0
ppft                      1.6.6.4
prometheus-client         0.11.0
prompt-toolkit            3.0.20
ptyprocess                0.7.0
py                        1.10.0
pyclits                   0.2
pycodestyle               2.7.0
pycparser                 2.20
pyflakes                  2.3.1
Pygments                  2.10.0
pyparsing                 2.4.7
pyproj                    3.2.1
pyrsistent                0.18.0
pyshp                     2.1.3
pytest                    6.2.5
python-dateutil           2.8.2
pytz                      2021.1
PyWavelets                1.1.1
pyzmq                     22.3.0
regex                     2021.8.28
requests                  2.26.0
requests-unixsocket       0.2.0
scikit-learn              0.24.2
scipy                     1.7.1
Send2Trash                1.8.0
setuptools                57.4.0
Shapely                   1.7.1
six                       1.16.0
smmap                     4.0.0
sniffio                   1.2.0
terminado                 0.12.1
testpath                  0.5.0
threadpoolctl             2.2.0
toml                      0.10.2
tomli                     1.2.1
tornado                   6.1
traitlets                 5.1.0
typed-ast                 1.4.3
typing-extensions         3.10.0.2
urllib3                   1.26.6
wcwidth                   0.2.5
webencodings              0.5.1
websocket-client          1.2.1
wheel                     0.37.0
widgetsnbextension        3.5.1
xarray                    0.19.0
zipp                      3.5.0
```

</details>

**Comment by jajcayn** [comment]
Update:
I was able to fix the problem... I was digging deeper and using `otool -L` on the shared library in question I found out `cartopy` is not linked to geos installation.
So I reinstalled, similarly as `shapely` with `pip install cartopy --no-binary cartopy`, and all works now.
Should I close, or leave it open for future reference?

**Comment by QuLogic** [comment]
I think we can close this then.
