### ISSUE TITLE
Cartopy installation fails with setuptools 61.0.0

### ISSUE THREAD

**Issue by glentakahashi** [SciTools/cartopy#2021]
### Description
Cartopy fails installation with setuptools>=61.0.0

#### Code to reproduce

```
pip install --upgrade setuptools==61.0.0
pip install Cartopy
```

#### Traceback 

```
pip install Cartopy==0.19.0.post1
Collecting Cartopy==0.19.0.post1
  Downloading Cartopy-0.19.0.post1.tar.gz (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 12.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/home/hexuser/.cache/pypoetry/virtualenvs/python-kernel-OtKFaj5M-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/hexuser/.cache/pypoetry/virtualenvs/python-kernel-OtKFaj5M-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/hexuser/.cache/pypoetry/virtualenvs/python-kernel-OtKFaj5M-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-2z3zk1ql/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-2z3zk1ql/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-2z3zk1ql/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 35, in <module>
          from setuptools import Command, Extension, convert_path, setup
      ImportError: cannot import name 'convert_path' from 'setuptools' (/tmp/pip-build-env-2z3zk1ql/overlay/lib/python3.8/site-packages/setuptools/__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

This is due to setuptools removing the import for `convert_path` from `distutils` in the latest version
https://github.com/pypa/setuptools/compare/v60.10.0...v61.0.0

**Comment by QuLogic** [comment]
Fixed by #2027.
