### ISSUE TITLE
Generate `ccrs.Globe` with datum specifiers other than the proj4 string datum ID

### ISSUE THREAD

**Issue by wjbenfold** [SciTools/cartopy#2039]
### Description

There isn't, as far as I can establish, a way to look up the required `datum` argument to a `ccrs.Globe` that will give the globe with a specific datum when starting with a datum name, code or any of the other information provided in a CF-compliant file. It would be useful to have doing so supported by Cartopy.

### Context

I'm currently attempting to add datum support to [Iris](https://github.com/SciTools/iris), which includes creating a Cartopy CRS from a netCDF file. Given the lack of a lookup from standard datum identification methods to the proj4 string representation, I'm currently resorting to a lookup dictionary in Iris but it feels that the lookup / alternative method belongs lower in the stack.

Is an alternative method of identifying the datum that a globe should be created with or a manner in which to look up the correct value to use something that you would consider adding to Cartopy?

**Comment by wjbenfold** [comment]
I hadn't tried deriving a `ccrs.Globe` like that, but I don't think it works?

```
>>> import cartopy.crs as ccrs
>>> import pyproj
>>> proj_crs = pyproj.CRS.from_user_input(26915)
>>> proj_crs
<Derived Projected CRS: EPSG:26915>
Name: NAD83 / UTM zone 15N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: North America - between 96°W and 90°W - onshore and offshore. Canada - Manitoba; Nunavut; Ontario. United States (USA) - Arkansas; Illinois; Iowa; Kansas; Louisiana; Michigan; Minnesota; Mississippi; Missouri; Nebraska; Oklahoma; Tennessee; Texas; Wisconsin.
- bounds: (-96.0, 25.61, -90.0, 84.0)
Coordinate Operation:
- name: UTM zone 15N
- method: Transverse Mercator
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

>>> cp_crs = ccrs.Projection(proj_crs)
>>> cp_crs
<Derived Projected CRS: EPSG:26915>
Name: NAD83 / UTM zone 15N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: North America - between 96°W and 90°W - onshore and offshore. Canada - Manitoba; Nunavut; Ontario. United States (USA) - Arkansas; Illinois; Iowa; Kansas; Louisiana; Michigan; Minnesota; Mississippi; Missouri; Nebraska; Oklahoma; Tennessee; Texas; Wisconsin.
- bounds: (-96.0, 25.61, -90.0, 84.0)
Coordinate Operation:
- name: UTM zone 15N
- method: Transverse Mercator
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

>>> print(cp_crs.globe)
None
```

I don't think I have another route to making a `PlateCarree` (or other `Projection` subclass) more directly from a pyproj CRS either?

**Comment by greglucas** [comment]
I guess the question is whether you need a Cartopy Globe at this point or if the Pyproj CRS has enough information directly associated with it already? This new `cp_crs` would replace the typical `PlateCarree()` calls.

You can do: `cp_crs.datum` and `cp_crs.ellipsoid` to access that information from pyproj if it is helpful.

**Comment by wjbenfold** [comment]
I think I'd then struggle to plot data using the `cp_crs` as it wouldn't have any of the attributes that Cartopy uses to distinguish plotting a `PlateCarree` and a `Mercator`? I'm fine with straight crs manipulation but getting to those subclasses doesn't seem possible without a `ccrs.Globe`

**Comment by wjbenfold** [comment]
Ah, sorry, I think my example was misleading because it included a CRS with an intrinsic projection. Iris has some CRSes without an intrinsic projection which this doesn't work for, e.g.

```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import pyproj

proj_crs = pyproj.crs.GeographicCRS(datum = "OSGB36")
cp_crs = ccrs.Projection(proj_crs)
fig = plt.figure()
ax = fig.add_subplot(projection=cp_crs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/h02/wbenfold/.conda/envs/iris-dev/lib/python3.8/site-packages/matplotlib/figure.py", line 772, in add_subplot
    ax = subplot_class_factory(projection_class)(self, *args, **pkw)
  File "/home/h02/wbenfold/.conda/envs/iris-dev/lib/python3.8/site-packages/matplotlib/axes/_subplots.py", line 34, in __init__
    self._axes_class.__init__(self, fig, [0, 0, 1, 1], **kwargs)
  File "/home/h02/wbenfold/.conda/envs/iris-dev/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 413, in __init__
    super().__init__(*args, **kwargs)
  File "/home/h02/wbenfold/.conda/envs/iris-dev/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)
  File "/home/h02/wbenfold/.conda/envs/iris-dev/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 632, in __init__
    self.cla()
  File "/home/h02/wbenfold/.conda/envs/iris-dev/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 607, in cla
    self._boundary()
  File "/home/h02/wbenfold/.conda/envs/iris-dev/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 1598, in _boundary
    path, = cpatch.geos_to_path(self.projection.boundary)
  File "/home/h02/wbenfold/.conda/envs/iris-dev/lib/python3.8/site-packages/cartopy/crs.py", line 672, in boundary
    raise NotImplementedError
NotImplementedError
```

Currently our approach is to make a Globe using the "OSGB36" datum and then to pass that to e.g. PlateCarree
