### ISSUE TITLE
Cartopy uses an older version of `proj` that is not specified in the install docs

### ISSUE THREAD

**Issue by ReagentX** [SciTools/cartopy#2043]
### Description
The steps provided are incorrect:

https://github.com/SciTools/cartopy/blob/ba25aee6c7868ee376ae7d0a52afea9a315ea623/INSTALL#L82-L98

#### Code to reproduce

```bash
~/project on b-docs                                                                              
❯ brew reinstall proj geos
==> Downloading https://ghcr.io/v2/homebrew/core/proj/manifests/9.0.0_1-1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/proj/blobs/sha256:6b0fc38c196c5cd32acc94a2b7092d56547f9515fcede56553081b0fb5232ed5
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:6b0fc38c196c5cd32acc94a2b7092d56547f9515fcede56553081b0fb5232ed5?se=2022-05-03T03%3A05%3A00Z&sig=5m3t
######################################################################## 100.0%
==> Reinstalling proj 
==> Pouring proj--9.0.0_1.monterey.bottle.1.tar.gz
🍺  /usr/local/Cellar/proj/9.0.0_1: 436 files, 588.0MB
==> Running `brew cleanup proj`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Downloading https://ghcr.io/v2/homebrew/core/geos/manifests/3.10.2
Already downloaded: ~/Library/Caches/Homebrew/downloads/a63029f2fdce8448826989aa39f0d9042297c483c25de741fddb5cd743f1ea29--geos-3.10.2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/geos/blobs/sha256:1a31f70c0017373e0f8676cfd69ddc3d7bcc3879010e60b0912a6103a4eeebbf
Already downloaded: ~/Library/Caches/Homebrew/downloads/8a8aa02cdd323de7cea0bffac1243421c471e3362c7c21c3bb32bcc7a04c10e5--geos--3.10.2.monterey.bottle.tar.gz
==> Reinstalling geos 
==> Pouring geos--3.10.2.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/geos/3.10.2: 483 files, 11.3MB
==> Running `brew cleanup geos`...
~/project on b-docs                                                                            took 33.50s Py 3.10.1 
❯ pip install --upgrade pyshp
Requirement already satisfied: pyshp in ./venv/lib/python3.10/site-packages (2.3.0)
~/project on b-docs                                                                             took 2.20s Py 3.10.1 
❯ pip uninstall shapely      
Found existing installation: Shapely 1.8.1.post1
Uninstalling Shapely-1.8.1.post1:
  Would remove:
    ~/project/venv/lib/python3.10/site-packages/Shapely-1.8.1.post1.dist-info/*
    ~/project/venv/lib/python3.10/site-packages/shapely/*
Proceed (Y/n)? Y
  Successfully uninstalled Shapely-1.8.1.post1
~/project on b-docs                                                                             took 5.85s Py 3.10.1 
❯ pip install install shapely --no-binary shapely
~/project on b-docs                                                                                  ✘ INT Py 3.10.1 
❯ pip install shapely --no-binary shapely
Collecting shapely
  Using cached Shapely-1.8.1.post1.tar.gz (198 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: shapely
  Building wheel for shapely (pyproject.toml) ... done
  Created wheel for shapely: filename=Shapely-1.8.1.post1-cp310-cp310-macosx_12_0_x86_64.whl size=315445 sha256=f2001326505c9e7e51e351c4c36d223cc83eb2b330f952219a2fa1e17c69b3c3
  Stored in directory: ~/Library/Caches/pip/wheels/f6/1a/94/d45a5da9bb46504d6be5aecc309f50ac62f146a17dc68efbd5
Successfully built shapely
Installing collected packages: shapely
Successfully installed shapely-1.8.1.post1
~/project on b-docs                                                                            took 31.08s Py 3.10.1  
❯ brew reinstall pkg-config
==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/manifests/0.29.2_3
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/blobs/sha256:a6ba80711f98b65d8a2bf2c9278540860415e9b5e545da338a4d94f39d119285
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:a6ba80711f98b65d8a2bf2c9278540860415e9b5e545da338a4d94f39d119285?se=2022-05-03T03%3A10%3A00Z&sig=31eA
######################################################################## 100.0%
==> Reinstalling pkg-config 
==> Pouring pkg-config--0.29.2_3.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.29.2_3: 11 files, 657KB
==> Running `brew cleanup pkg-config`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
~/project on b-docs                                                                             took 5.73s Py 3.10.1 
❯ export PKG_CONFIG_PATH=/usr/local/bin/pkgconfig
~/project on b-docs                                                                             took 0.02s Py 3.10.1 
❯ pip install cartopy                          
Collecting cartopy
  Using cached Cartopy-0.20.2-cp310-cp310-macosx_12_0_x86_64.whl
Requirement already satisfied: pyshp>=2.1 in ./venv/lib/python3.10/site-packages (from cartopy) (2.3.0)
Requirement already satisfied: shapely>=1.6.4 in ./venv/lib/python3.10/site-packages (from cartopy) (1.8.1.post1)
Requirement already satisfied: pyproj>=3.0.0 in ./venv/lib/python3.10/site-packages (from cartopy) (3.3.0)
Requirement already satisfied: numpy>=1.18 in ./venv/lib/python3.10/site-packages (from cartopy) (1.22.2)
Requirement already satisfied: matplotlib>=3.1 in ./venv/lib/python3.10/site-packages (from cartopy) (3.5.1)
Requirement already satisfied: kiwisolver>=1.0.1 in ./venv/lib/python3.10/site-packages (from matplotlib>=3.1->cartopy) (1.3.2)
Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.10/site-packages (from matplotlib>=3.1->cartopy) (21.3)
Requirement already satisfied: cycler>=0.10 in ./venv/lib/python3.10/site-packages (from matplotlib>=3.1->cartopy) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in ./venv/lib/python3.10/site-packages (from matplotlib>=3.1->cartopy) (3.0.7)
Requirement already satisfied: python-dateutil>=2.7 in ./venv/lib/python3.10/site-packages (from matplotlib>=3.1->cartopy) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in ./venv/lib/python3.10/site-packages (from matplotlib>=3.1->cartopy) (4.29.1)
Requirement already satisfied: pillow>=6.2.0 in ./venv/lib/python3.10/site-packages (from matplotlib>=3.1->cartopy) (9.0.1)
Requirement already satisfied: certifi in ./venv/lib/python3.10/site-packages (from pyproj>=3.0.0->cartopy) (2021.10.8)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.1->cartopy) (1.16.0)
Installing collected packages: cartopy
Successfully installed cartopy-0.20.2
```

#### Traceback 

```
Traceback (most recent call last):
  File "~/project/scripts/plot_map.py", line 7, in <module>
    import cartopy.crs as ccrs
  File "~/project/venv/lib/python3.10/site-packages/cartopy/__init__.py", line 107, in <module>
    import cartopy.crs
  File "~/project/venv/lib/python3.10/site-packages/cartopy/crs.py", line 27, in <module>
    import cartopy.trace
ImportError: dlopen(~/project/venv/lib/python3.10/site-packages/cartopy/trace.cpython-310-darwin.so, 0x0002): Library not loaded: /usr/local/opt/proj/lib/libproj.22.dylib
  Referenced from: ~/project/venv/lib/python3.10/site-packages/cartopy/trace.cpython-310-darwin.so
  Reason: tried: '/usr/local/opt/proj/lib/libproj.22.dylib' (no such file), '/usr/local/lib/libproj.22.dylib' (no such file), '/usr/lib/libproj.22.dylib' (no such file), '/usr/local/Cellar/proj/9.0.0_1/lib/libproj.22.dylib' (no such file), '/usr/local/lib/libproj.22.dylib' (no such file), '/usr/lib/libproj.22.dylib' (no such file)
```

<details>
 <summary>Full environment definition</summary>

### Operating system

MacOS `12.3.1 (21E258)`

### Cartopy version

`cartopy-0.20.2`

### pip list

```
pyshp
shapely
pyproj
numpy
matplotlib
kiwisolver
packaging
cycler
pyparsing
python
fonttools
pillow
certifi
six
```

</details>

**Comment by ReagentX** [comment]
Per the trace, `cartopy` looks in several places for `proj`:

```
  '/usr/local/opt/proj/lib/libproj.22.dylib'
  '/usr/local/lib/libproj.22.dylib'
  '/usr/lib/libproj.22.dylib'
  '/usr/local/Cellar/proj/9.0.0_1/lib/libproj.22.dylib'
  '/usr/local/lib/libproj.22.dylib'
  '/usr/lib/libproj.22.dylib'  
```

The path brew installs in is no longer `/usr/local/Cellar/`. Per the `brew` man page:

```
--prefix [--unbrewed] [--installed] [formula ...]
       Display Homebrew´s install path. Default:

       •   macOS Intel: /usr/local

       •   macOS ARM: /opt/homebrew

       •   Linux: /home/linuxbrew/.linuxbrew
```

**Comment by ReagentX** [comment]
I was able to resolve this by using the following commands to force `cartopy` to build with the required dependencies:

```zsh
❯ pip uninstall -y pyproj cartopy
❯  pip install pyproj --no-binary pyproj
❯ pip install cartopy --no-binary cartopy
```

**Comment by greglucas** [comment]
Thanks for posting all of that and I'm glad you got it worked out, @ReagentX! Would you be interested in updating the documentation about how to install with the necessary requirements you found?
