### ISSUE TITLE
cartopy.crs.epsg() failing (again)

### ISSUE THREAD

**Issue by itati01** [SciTools/cartopy#2064]
### Description

Cartopy fails when attempting to define an EPSG crs. This is similar to the closed issue #1437. The identical code worked 5 days ago.

#### Code to reproduce

```
import cartopy.crs as ccrs
ccrs.epsg(3035)
```

#### Traceback 

```
Traceback (most recent call last):
  File "C:\**\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-aedc3ea5b539>", line 1, in <module>
    ccrs.epsg(3035)
  File "C:\**\Anaconda3\lib\site-packages\cartopy\crs.py", line 2557, in epsg
    return cartopy._epsg._EPSGProjection(code)
  File "C:\**\Anaconda3\lib\site-packages\cartopy\_epsg.py", line 43, in __init__
    projection = pyepsg.get(code)
  File "C:\**\Anaconda3\lib\site-packages\pyepsg.py", line 288, in get
    root = ET.fromstring(xml)
  File "C:\**\Anaconda3\lib\xml\etree\ElementTree.py", line 1320, in XML
    parser.feed(text)
  File "<string>", line unknown
ParseError: not well-formed (invalid token): line 1, column 0
```

<details>
 <summary>Full environment definition</summary>

### Operating system
Windows 10

### Cartopy version
0.18.0 installed via conda

### conda list

```
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0
affine                    2.3.0              pyhd3eb1b0_0
alabaster                 0.7.12             pyhd3eb1b0_0
anaconda-client           1.9.0            py38haa95532_0
anaconda-navigator        2.1.1                    py38_0
anyio                     2.2.0            py38haa95532_2
appdirs                   1.4.4              pyhd3eb1b0_0
argon2-cffi               20.1.0           py38h2bbff1b_1
arrow                     0.13.1                   py38_0
astroid                   2.6.6            py38haa95532_0
async_generator           1.10               pyhd3eb1b0_0
atomicwrites              1.4.0                      py_0
attrs                     21.4.0             pyhd3eb1b0_0
autopep8                  1.6.0              pyhd3eb1b0_0
babel                     2.9.1              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
backports                 1.1                pyhd3eb1b0_0
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0
backports.tempfile        1.0                pyhd3eb1b0_1
backports.weakref         1.0.post1                  py_1
bcrypt                    3.2.0            py38he774522_0
beautifulsoup4            4.10.0             pyh06a4308_0
binaryornot               0.4.4              pyhd3eb1b0_1
black                     19.10b0                    py_0
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
blosc                     1.21.0               h19a0ad4_0
bottleneck                1.3.2            py38h2a96729_1
brotli                    1.0.9                ha925a31_2
brotlipy                  0.7.0           py38h2bbff1b_1003
bzip2                     1.0.8                he774522_0
ca-certificates           2022.6.15            h5b45459_0    conda-forge
cartopy                   0.18.0           py38h80a4efb_1
certifi                   2022.6.15        py38haa244fe_0    conda-forge
cffi                      1.15.0           py38h2bbff1b_1
cfitsio                   3.470                he774522_6
cftime                    1.5.1.1          py38h080aedc_0
chardet                   4.0.0           py38haa95532_1003
charls                    2.2.0                h6c2663c_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     7.1.2              pyhd3eb1b0_0
click-plugins             1.1.1              pyhd3eb1b0_0
cligj                     0.7.2            py38haa95532_0
cloudpickle               2.0.0              pyhd3eb1b0_0
clyent                    1.2.2                    py38_1
colorama                  0.4.4              pyhd3eb1b0_0
conda                     4.13.0           py38haa244fe_1    conda-forge
conda-build               3.21.6           py38haa95532_0
conda-content-trust       0.1.1              pyhd3eb1b0_0
conda-env                 2.6.0                         1
conda-package-handling    1.7.3            py38h8cc25b3_1
conda-repo-cli            1.0.4              pyhd3eb1b0_0
conda-token               0.3.0              pyhd3eb1b0_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
cookiecutter              1.7.2              pyhd3eb1b0_0
cryptography              3.4.8            py38h71e12ea_0
cudatoolkit               10.1.243             h74a9793_0
cudnn                     7.6.5                cuda10.1_0
cupy                      8.3.0            py38hd4ca531_0
curl                      7.80.0               h2bbff1b_0
cycler                    0.11.0             pyhd3eb1b0_0
cython                    0.29.25          py38h604cdb4_0
cytoolz                   0.11.0           py38he774522_0
dask-core                 2021.10.0          pyhd3eb1b0_0
debugpy                   1.5.1            py38hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713           pyhd3eb1b0_0
docutils                  0.17.1           py38haa95532_1
entrypoints               0.3                      py38_0
et_xmlfile                1.1.0            py38haa95532_0
expat                     2.4.1                h6c2663c_2
fastrlock                 0.6              py38hd77b12b_0
filelock                  3.4.2              pyhd3eb1b0_0
fiona                     1.8.13.post1     py38h758c064_0
flake8                    3.9.2              pyhd3eb1b0_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.10.4               hd328e21_0
freexl                    1.0.6                h2bbff1b_0
fsspec                    2022.1.0           pyhd3eb1b0_0
future                    0.18.2                   py38_1
gdal                      3.0.2            py38hb978731_1
geojson                   2.5.0                      py_0    conda-forge
geopandas                 0.9.0                      py_1
geopandas-base            0.9.0                      py_1
geos                      3.8.0                h33f27b4_0
geotiff                   1.6.0                h5770a2b_0
giflib                    5.2.1                h62dcd97_0
glob2                     0.7                pyhd3eb1b0_0
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.6               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       68.1                 h6c2663c_0
idna                      3.3                pyhd3eb1b0_0
imagecodecs               2021.8.26        py38ha1f97ea_0
imageio                   2.9.0              pyhd3eb1b0_0
imagesize                 1.3.0              pyhd3eb1b0_0
importlib-metadata        4.8.2            py38haa95532_0
importlib_metadata        4.8.2                hd3eb1b0_0
inflection                0.5.1            py38haa95532_0
iniconfig                 1.1.1              pyhd3eb1b0_0
intel-openmp              2021.4.0          haa95532_3556
intervaltree              3.1.0              pyhd3eb1b0_0
ipykernel                 6.4.1            py38haa95532_1
ipython                   7.29.0           py38hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.5              pyhd3eb1b0_1
isort                     5.9.3              pyhd3eb1b0_0
jedi                      0.18.0           py38haa95532_1
jinja2                    2.11.3             pyhd3eb1b0_0
jinja2-time               0.2.0              pyhd3eb1b0_2
joblib                    1.1.0              pyhd3eb1b0_0
jpeg                      9d                   h2bbff1b_0
json5                     0.9.6              pyhd3eb1b0_0
jsonschema                3.2.0              pyhd3eb1b0_2
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_core              4.9.1            py38haa95532_0
jupyter_server            1.4.1            py38haa95532_0
jupyterlab                3.2.1              pyhd3eb1b0_1
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.10.2             pyhd3eb1b0_1
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
kealib                    1.4.14               hde4a422_1
keyring                   23.4.0           py38haa95532_0
kiwisolver                1.3.1            py38hd77b12b_0
krb5                      1.19.2               h5b6d351_0
lazy-object-proxy         1.6.0            py38h2bbff1b_0
lcms2                     2.12                 h83e58a3_0
lerc                      3.0                  hd77b12b_0
libaec                    1.0.4                h33f27b4_1
libarchive                3.4.2                h5e25573_0
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.80.0               h86230a5_0
libdeflate                1.8                  h2bbff1b_5
libgdal                   3.0.2                ha1b3edf_1
libiconv                  1.16                 he774522_0    conda-forge
liblief                   0.10.1               ha925a31_0
libnetcdf                 4.6.1                hf59b723_4
libpng                    1.6.37               h2a8f88b_0
libpq                     12.9                 hb652d5d_1
libspatialindex           1.9.3                h6c2663c_0
libspatialite             4.3.0a              h14feca5_20
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.2.0                hd0e1b90_0
libwebp                   1.2.0                h2bbff1b_0
libxml2                   2.9.12               h0ad7f3c_0
libzopfli                 1.0.3                ha925a31_0
lineedit                  0.1.6              pyhd8ed1ab_0    conda-forge
llvmlite                  0.37.0           py38h23ce68f_1
locket                    0.2.1            py38haa95532_1
lz4-c                     1.9.3                h2bbff1b_1
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
mapclassify               2.4.3              pyhd3eb1b0_0
markupsafe                1.1.1            py38he774522_0
matplotlib                3.5.1            py38haa95532_1
matplotlib-base           3.5.1            py38hd77b12b_1
matplotlib-inline         0.1.2              pyhd3eb1b0_2
matplotlib-scalebar       0.8.1                    pypi_0    pypi
mccabe                    0.6.1                    py38_1
menuinst                  1.4.18           py38h59b6b97_0
mistune                   0.8.4           py38he774522_1000
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py38h2bbff1b_0
mkl_fft                   1.3.1            py38h277e83a_0
mkl_random                1.2.2            py38hf11a4ad_0
more-itertools            8.12.0             pyhd3eb1b0_0
msys2-conda-epoch         20160418                      1
munch                     2.5.0              pyhd3eb1b0_0
munkres                   1.1.4                      py_0
mypy_extensions           0.4.3            py38haa95532_1
navigator-updater         0.2.1                    py38_0
nbclassic                 0.2.6              pyhd3eb1b0_0
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.1.0            py38haa95532_0
nbformat                  5.1.3              pyhd3eb1b0_0
nest-asyncio              1.5.1              pyhd3eb1b0_0
netcdf4                   1.5.7            py38hb33177a_0
networkx                  2.6.3              pyhd3eb1b0_0
notebook                  6.4.6            py38haa95532_0
numba                     0.54.1           py38hf11a4ad_0
numexpr                   2.8.1            py38hb80d3ca_0
numpy                     1.20.3           py38ha4e8547_0
numpy-base                1.20.3           py38hc2deb75_0
numpydoc                  1.2                pyhd3eb1b0_0
olefile                   0.46               pyhd3eb1b0_0
openjpeg                  2.4.0                h4fc8c34_0
openpyxl                  3.0.9              pyhd3eb1b0_0
openssl                   1.1.1p               h8ffe710_0    conda-forge
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.3.5            py38h6214cd6_0
pandocfilters             1.5.0              pyhd3eb1b0_0
paramiko                  2.8.1              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
partd                     1.2.0              pyhd3eb1b0_0
pathspec                  0.7.0                      py_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.4.0            py38hd45dc43_0
pip                       21.2.2           py38haa95532_0
pkginfo                   1.8.2              pyhd3eb1b0_0
plotly                    5.6.0              pyhd3eb1b0_0
pluggy                    0.13.1           py38haa95532_0
postgresql                12.9                 hb652d5d_1
powershell_shortcut       0.0.1                         3
poyo                      0.5.0              pyhd3eb1b0_0
proj                      6.2.1                h3758d61_0
prometheus_client         0.13.1             pyhd3eb1b0_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
psutil                    5.8.0            py38h2bbff1b_1
ptyprocess                0.7.0              pyhd3eb1b0_2
py                        1.10.0             pyhd3eb1b0_0
py-lief                   0.10.1           py38ha925a31_0
pycodestyle               2.7.0              pyhd3eb1b0_0
pycosat                   0.6.3            py38h2bbff1b_0
pycparser                 2.21               pyhd3eb1b0_0
pydocstyle                6.1.1              pyhd3eb1b0_0
pyepsg                    0.4.0              pyhd3eb1b0_0
pyflakes                  2.3.1              pyhd3eb1b0_0
pygeos                    0.9              py38ha9a577c_1    conda-forge
pygments                  2.10.0             pyhd3eb1b0_0
pyjwt                     2.1.0            py38haa95532_0
pylint                    2.9.6            py38haa95532_1
pyls-spyder               0.4.0              pyhd3eb1b0_0
pynacl                    1.4.0            py38h62dcd97_1
pyopenssl                 21.0.0             pyhd3eb1b0_1
pyparsing                 3.0.4              pyhd3eb1b0_0
pyproj                    2.6.1.post1      py38h593ac45_1
pyqt                      5.12.3           py38haa244fe_7    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_7    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_7    conda-forge
pyqtchart                 5.12             py38h885f38d_7    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_7    conda-forge
pyrsistent                0.18.0           py38h196d8e1_0
pysheds                   0.3.2                     dev_0    <develop>
pyshp                     2.1.3              pyhd3eb1b0_0
pysocks                   1.7.1            py38haa95532_0
pytest                    6.2.4            py38haa95532_2
python                    3.8.12               h6244533_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python-libarchive-c       2.9                pyhd3eb1b0_1
python-lsp-black          1.0.0              pyhd3eb1b0_0
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0
python-lsp-server         1.2.4              pyhd3eb1b0_0
python-slugify            5.0.2              pyhd3eb1b0_0
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3                   pypi_0    pypi
pywavelets                1.1.1            py38he774522_2
pywin32                   302              py38h827c3e9_1
pywin32-ctypes            0.2.0                 py38_1000
pywinpty                  0.5.7                    py38_0
pyyaml                    6.0              py38h2bbff1b_1
pyzmq                     22.3.0           py38hd77b12b_2
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.1.10             pyhd3eb1b0_0
qt                        5.12.9               h5909a2a_4    conda-forge
qtawesome                 1.0.3              pyhd3eb1b0_0
qtconsole                 5.1.1              pyhd3eb1b0_0
qtpy                      1.11.2             pyhd3eb1b0_0
radian                    0.5.12             pyhd8ed1ab_0    conda-forge
rasterio                  1.1.1            py38h2617b1b_0    conda-forge
rchitect                  0.3.33           py38h294d835_1    conda-forge
regex                     2021.8.3         py38h2bbff1b_0
requests                  2.27.1             pyhd3eb1b0_0
rioxarray                 0.9.1              pyhd8ed1ab_0    conda-forge
rope                      0.22.0             pyhd3eb1b0_0
rtree                     0.9.7            py38h2eaa2aa_1
ruamel_yaml               0.15.100         py38h2bbff1b_0
scikit-image              0.18.3           py38hf11a4ad_0
scikit-learn              1.0.2            py38hf11a4ad_1
scipy                     1.7.3            py38h0a974cb_0
seaborn                   0.11.2             pyhd3eb1b0_0
send2trash                1.8.0              pyhd3eb1b0_1
setuptools                58.0.4           py38haa95532_0
shapely                   1.7.1            py38h06580b3_0
simpledbf                 0.2.6                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_0
snappy                    1.1.8                h33f27b4_0
sniffio                   1.2.0            py38haa95532_1
snowballstemmer           2.2.0              pyhd3eb1b0_0
snuggs                    1.4.7              pyhd3eb1b0_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
soupsieve                 2.3.1              pyhd3eb1b0_0
sphinx                    4.4.0              pyhd3eb1b0_0
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0
spyder                    5.1.5            py38haa95532_1
spyder-kernels            2.1.3            py38haa95532_0
sqlite                    3.37.0               h2bbff1b_0
tbb                       2021.5.0             h59b6b97_0
tenacity                  8.0.1            py38haa95532_0
terminado                 0.9.4            py38haa95532_0
testpath                  0.5.0              pyhd3eb1b0_0
text-unidecode            1.3                pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
threadpoolctl             2.2.0              pyh0d69192_0
three-merge               0.1.1              pyhd3eb1b0_0
tifffile                  2021.7.2           pyhd3eb1b0_2
tiledb                    2.2.9                hf84e3da_0    conda-forge
tinycss                   0.4             pyhd3eb1b0_1002
tk                        8.6.11               h2bbff1b_0
toml                      0.10.2             pyhd3eb1b0_0
toolz                     0.11.2             pyhd3eb1b0_0
topojson                  1.4                pyhd8ed1ab_0    conda-forge
tornado                   6.1              py38h2bbff1b_0
tqdm                      4.62.3             pyhd3eb1b0_1
traitlets                 5.1.1              pyhd3eb1b0_0
typed-ast                 1.4.3            py38h2bbff1b_1
typing-extensions         3.10.0.2             hd3eb1b0_0
typing_extensions         3.10.0.2           pyh06a4308_0
ujson                     4.0.2            py38hd77b12b_0
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   1.26.8             pyhd3eb1b0_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  2.1.6            py38haa95532_0
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1                    py38_1
wheel                     0.37.1             pyhd3eb1b0_0
whichcraft                0.6.1              pyhd3eb1b0_0
widgetsnbextension        3.5.1                    py38_0
win_inet_pton             1.1.0            py38haa95532_0
wincertstore              0.2              py38haa95532_2
winpty                    0.4.3                         4
wordcloud                 1.8.1            py38h294d835_1    conda-forge
wrapt                     1.12.1           py38he774522_1
xarray                    0.20.1             pyhd3eb1b0_1
xerces-c                  3.2.3                ha925a31_0
xmltodict                 0.12.0             pyhd3eb1b0_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
yapf                      0.31.0             pyhd3eb1b0_0
zfp                       0.5.5                hd77b12b_6
zipp                      3.7.0              pyhd3eb1b0_0
zlib                      1.2.11               h8cc25b3_4
zstd                      1.4.9                h19a0ad4_0
```

### pip list

```
Package                       Version      Location
----------------------------- ------------ --------------------------------------------
affine                        2.3.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.1.1
anyio                         2.2.0
appdirs                       1.4.4
argon2-cffi                   20.1.0
arrow                         0.13.1
astroid                       2.6.6
async-generator               1.10
atomicwrites                  1.4.0
attrs                         21.4.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
beautifulsoup4                4.10.0
binaryornot                   0.4.4
black                         19.10b0
bleach                        4.1.0
Bottleneck                    1.3.2
brotlipy                      0.7.0
Cartopy                       0.18.0
certifi                       2022.6.15
cffi                          1.15.0
cftime                        1.5.1.1
chardet                       4.0.0
charset-normalizer            2.0.4
click                         7.1.2
click-plugins                 1.1.1
cligj                         0.7.2
cloudpickle                   2.0.0
clyent                        1.2.2
colorama                      0.4.4
conda                         4.13.0
conda-build                   3.21.6
conda-content-trust           0+unknown
conda-package-handling        1.7.3
conda-repo-cli                1.0.4
conda-token                   0.3.0
conda-verify                  3.4.2
cookiecutter                  1.7.2
cryptography                  3.4.8
cupy                          8.3.0
cycler                        0.11.0
Cython                        0.29.25
cytoolz                       0.11.0
dask                          2021.10.0
debugpy                       1.5.1
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
docutils                      0.17.1
entrypoints                   0.3
et-xmlfile                    1.1.0
fastrlock                     0.6
filelock                      3.4.2
Fiona                         1.8.13.post1
flake8                        3.9.2
fonttools                     4.25.0
fsspec                        2022.1.0
future                        0.18.2
GDAL                          3.0.2
geojson                       2.5.0
geopandas                     0.9.0
glob2                         0.7
idna                          3.3
imagecodecs                   2021.8.26
imageio                       2.9.0
imagesize                     1.3.0
importlib-metadata            4.8.2
inflection                    0.5.1
iniconfig                     1.1.1
intervaltree                  3.1.0
ipykernel                     6.4.1
ipython                       7.29.0
ipython-genutils              0.2.0
ipywidgets                    7.6.5
isort                         5.9.3
jedi                          0.18.0
Jinja2                        2.11.3
jinja2-time                   0.2.0
joblib                        1.1.0
json5                         0.9.6
jsonschema                    3.2.0
jupyter-client                6.1.12
jupyter-core                  4.9.1
jupyter-server                1.4.1
jupyterlab                    3.2.1
jupyterlab-pygments           0.1.2
jupyterlab-server             2.10.2
jupyterlab-widgets            1.0.0
keyring                       23.4.0
kiwisolver                    1.3.1
lazy-object-proxy             1.6.0
libarchive-c                  2.9
lineedit                      0.1.6
llvmlite                      0.37.0
locket                        0.2.1
mapclassify                   2.4.3
MarkupSafe                    1.1.1
matplotlib                    3.5.1
matplotlib-inline             0.1.2
matplotlib-scalebar           0.8.1
mccabe                        0.6.1
menuinst                      1.4.18
mistune                       0.8.4
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
more-itertools                8.12.0
munch                         2.5.0
munkres                       1.1.4
mypy-extensions               0.4.3
navigator-updater             0.2.1
nbclassic                     0.2.6
nbclient                      0.5.3
nbconvert                     6.1.0
nbformat                      5.1.3
nest-asyncio                  1.5.1
netCDF4                       1.5.7
networkx                      2.6.3
notebook                      6.4.6
numba                         0.54.1
numexpr                       2.8.1
numpy                         1.20.3
numpydoc                      1.2
olefile                       0.46
openpyxl                      3.0.9
packaging                     21.3
pandas                        1.3.5
pandocfilters                 1.5.0
paramiko                      2.8.1
parso                         0.8.3
partd                         1.2.0
pathspec                      0.7.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.4.0
pip                           21.2.2
pkginfo                       1.8.2
plotly                        5.6.0
pluggy                        0.13.1
poyo                          0.5.0
prometheus-client             0.13.1
prompt-toolkit                3.0.20
psutil                        5.8.0
ptyprocess                    0.7.0
py                            1.10.0
pycodestyle                   2.7.0
pycosat                       0.6.3
pycparser                     2.21
pydocstyle                    6.1.1
pyepsg                        0.4.0
pyflakes                      2.3.1
pygeos                        0.9
Pygments                      2.10.0
PyJWT                         2.1.0
pylint                        2.9.6
pyls-spyder                   0.4.0
PyNaCl                        1.4.0
pyOpenSSL                     21.0.0
pyparsing                     3.0.4
pyproj                        2.6.1.post1
PyQt5                         5.12.3
PyQt5_sip                     4.19.18
PyQtChart                     5.12
PyQtWebEngine                 5.12.1
pyrsistent                    0.18.0
pysheds                       0.3.2
pyshp                         2.1.3
PySocks                       1.7.1
pytest                        6.2.4
python-dateutil               2.8.2
python-lsp-black              1.0.0
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.2.4
python-slugify                5.0.2
pytz                          2021.3
PyWavelets                    1.1.1
pywin32                       302
pywin32-ctypes                0.2.0
pywinpty                      0.5.7
PyYAML                        6.0
pyzmq                         22.3.0
QDarkStyle                    3.0.2
qstylizer                     0.1.10
QtAwesome                     1.0.3
qtconsole                     5.1.1
QtPy                          1.11.2
radian                        0.5.12
rasterio                      1.1.1
rchitect                      0.3.33
regex                         2021.8.3
requests                      2.27.1
rioxarray                     0.9.1
rope                          0.22.0
Rtree                         0.9.7
ruamel-yaml-conda             0.15.100
scikit-image                  0.18.3
scikit-learn                  1.0.2
scipy                         1.7.3
seaborn                       0.11.2
Send2Trash                    1.8.0
setuptools                    58.0.4
Shapely                       1.7.1
simpledbf                     0.2.6
six                           1.16.0
sniffio                       1.2.0
snowballstemmer               2.2.0
snuggs                        1.4.7
sortedcontainers              2.4.0
soupsieve                     2.3.1
Sphinx                        4.4.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.1.5
spyder-kernels                2.1.3
tenacity                      8.0.1
terminado                     0.9.4
testpath                      0.5.0
text-unidecode                1.3
textdistance                  4.2.1
threadpoolctl                 2.2.0
three-merge                   0.1.1
tifffile                      2021.7.2
tinycss                       0.4
toml                          0.10.2
toolz                         0.11.2
topojson                      1.4
tornado                       6.1
tqdm                          4.62.3
traitlets                     5.1.1
typed-ast                     1.4.3
typing-extensions             3.10.0.2
ujson                         4.0.2
Unidecode                     1.2.0
urllib3                       1.26.8
watchdog                      2.1.6
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.37.1
whichcraft                    0.6.1
widgetsnbextension            3.5.1
win-inet-pton                 1.1.0
wincertstore                  0.2
wordcloud                     1.8.1
wrapt                         1.12.1
xarray                        0.20.1
xmltodict                     0.12.0
yapf                          0.31.0
zipp                          3.7.0
```

</details>

**Comment by greglucas** [comment]
It looks like you are on Cartopy v0.18.0, The most recent Cartopy releases have removed the webservice, so this should only affect older Cartopy versions and I'm not sure we can do anything about it unfortunately :(

The suggestion is to upgrade your version of Cartopy.

**Comment by itati01** [comment]
Unfortunately, conda only offers 0.18 even with in a new virtual env. Do have any idea how to proceed?

**Comment by itati01** [comment]
Even with freshly installed Anaconda and Miniconda (both Python 3.9), `conda -c conda-forge cartopy ` suggests 0.18. Although, I can install proj 8.2.1, conda suggests to downgrade it when I try to install cartopy. However, I am able to install 0.20.3 under Linux (Ubuntu).

**Comment by saastra** [comment]
The problem seems to be with a dependency the [pyepsg](https://pypi.org/project/pyepsg/) package. There is a known [issue](https://github.com/rhattersley/pyepsg/issues/22) since august, as the server from which it retrieves epsg information stopped sending gml format and switched to json. It doesn't seem, there's going to be a solution anytime soon.

**Comment by greglucas** [comment]
pyepsg is no longer a dependency, the epsg work is all handled by pyproj now. So, there is really nothing we can do here, the solution is to upgrade your Cartopy version.
