### ISSUE TITLE
Correct way to check matplotlib version

### ISSUE THREAD

**Issue by zxdawn** [SciTools/cartopy#2237]
#### Code to reproduce

```
import cartopy
```

#### Traceback

```
>>> import cartopy.mpl.geocollection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xinz/miniconda3/envs/test_cartopy/lib/python3.10/site-packages/cartopy/mpl/geocollection.py", line 13, in <module>
    _MPL_VERSION = packaging.version.parse(mpl.__version__)
AttributeError: module 'packaging' has no attribute 'version'
```

#### Solution

Modify the `geocollection.py`:

```
from packaging import version

_MPL_VERSION = version.parse(mpl.__version__)
```

<details>
 <summary>Full environment definition</summary>

### Operating system

Mac M1

### Cartopy version

0.22.0

### conda list

```
# Name                    Version                   Build  Channel
brotli                    1.0.9                h1a8c8d9_9    conda-forge
brotli-bin                1.0.9                h1a8c8d9_9    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.19.1               hb547adb_0    conda-forge
ca-certificates           2023.7.22            hf0a4a13_0    conda-forge
cartopy                   0.22.0          py310h1cdf563_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
contourpy                 1.1.0           py310h38f39d4_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
fonttools                 4.42.1          py310h2aa6e3c_0    conda-forge
freetype                  2.12.1               hd633e50_1    conda-forge
geos                      3.12.0               h13dd4ca_0    conda-forge
kiwisolver                1.4.4           py310h2887b22_1    conda-forge
krb5                      1.21.2               h92f50d5_0    conda-forge
lcms2                     2.15                 hd835a16_1    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libblas                   3.9.0           17_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h1a8c8d9_9    conda-forge
libbrotlidec              1.0.9                h1a8c8d9_9    conda-forge
libbrotlienc              1.0.9                h1a8c8d9_9    conda-forge
libcblas                  3.9.0           17_osxarm64_openblas    conda-forge
libcurl                   8.2.1                hc52a3a8_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libdeflate                1.18                 h1a8c8d9_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           12_3_0_hd922786_1    conda-forge
libgfortran5              12.3.0               ha3a6a3e_1    conda-forge
libjpeg-turbo             2.1.5.1              h1a8c8d9_0    conda-forge
liblapack                 3.9.0           17_osxarm64_openblas    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libopenblas               0.3.23          openmp_hc731615_0    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libsqlite                 3.42.0               hb31c410_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libtiff                   4.5.1                h23a1a89_0    conda-forge
libwebp-base              1.3.1                hb547adb_0    conda-forge
libxcb                    1.15                 hf346824_0    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
llvm-openmp               16.0.6               h1c12783_0    conda-forge
matplotlib-base           3.4.3           py310hacb9267_2    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.4                  h7ea286d_0    conda-forge
numpy                     1.25.2          py310haa1e00c_0    conda-forge
openjpeg                  2.5.0                hbc2ba62_2    conda-forge
openssl                   3.1.2                h53f4e23_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pillow                    10.0.0          py310h60ecbdf_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
proj                      9.2.1                h8fdea58_0    conda-forge
proplot                   0.9.7              pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyproj                    3.6.0           py310had6ea04_1    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
python                    3.10.12         h01493a6_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
setuptools                68.1.2             pyhd8ed1ab_0    conda-forge
shapely                   2.0.1           py310h76ac421_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.42.0               h203b68d_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
tornado                   6.3.3           py310h2aa6e3c_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
unicodedata2              15.0.0          py310h8e9501a_0    conda-forge
wheel                     0.41.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
zstd                      1.5.2                h4f39d0f_7    conda-forge
```

### pip list

```
Package         Version
--------------- ---------
Cartopy         0.22.0
certifi         2023.7.22
contourpy       1.1.0
cycler          0.11.0
fonttools       4.42.1
kiwisolver      1.4.4
matplotlib      3.4.3
munkres         1.1.4
numpy           1.25.2
packaging       23.1
Pillow          10.0.0
pip             23.2.1
proplot         0.9.7
pyparsing       3.0.9
pyproj          3.6.0
pyshp           2.3.1
python-dateutil 2.8.2
setuptools      68.1.2
shapely         2.0.1
six             1.16.0
tornado         6.3.3
unicodedata2    15.0.0
wheel           0.41.1
```

</details>

**Comment by rcomer** [comment]
I cannot seem to reproduce this on my Linux machine, but I agree the imports here should have been more explicit.  #2238 should fix.
