### ISSUE TITLE
Cannot import cartopy.feature (missing 'config')

### ISSUE THREAD

**Issue by Elizabethcase** [SciTools/cartopy#2315]
### Description
I'm a first time cartopy user. It installed just fine, but when I try to import cartopy.feature I get an import error related to the config file. As far as I can tell, this _should_ be made automatically by the `__init__` file, but this doesn't seem to be the case. 

#### Code to reproduce

```
import cartopy.feature as ccrs
```

#### Traceback

```
Traceback (most recent call last):
  File "/Users/elizabeth/mambaforge/envs/IMAU/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 9, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/elizabeth/mambaforge/envs/IMAU/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 19, in <module>
    import cartopy.io.shapereader as shapereader
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/elizabeth/mambaforge/envs/IMAU/lib/python3.10/site-packages/cartopy/io/__init__.py", line 19, in <module>
    from cartopy import config
ImportError: cannot import name 'config' from 'cartopy' (unknown location)
```

<details>

### Operating system

Version:
Python: 3.10
MacOS: Sonoma 14.2.1 (Apple M1)

### Cartopy version
 0.22.0

</details>

**Comment by Elizabethcase** [comment]
nevermind, sorry, this was an environment problem.
