### ISSUE TITLE
TypeError running GlobalMap example

### ISSUE THREAD

**Issue by crotwell** [SciTools/cartopy#2423]
### Description

Running the example here:
https://scitools.org.uk/cartopy/docs/latest/gallery/lines_and_polygons/global_map.html#sphx-glr-gallery-lines-and-polygons-global-map-py
get
```
TypeError: ufunc 'create_collection' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Feels like might be related to numpy2 NEP50?

#### Code to reproduce

```
import matplotlib.pyplot as plt

import cartopy.crs as ccrs


def main():
    fig = plt.figure(figsize=(10, 5))
    ax = fig.add_subplot(1, 1, 1, projection=ccrs.Robinson())

    # make the map global rather than have it zoom in to
    # the extents of any plotted data
    ax.set_global()

    ax.stock_img()
    ax.coastlines()

    ax.plot(-0.08, 51.53, 'o', transform=ccrs.PlateCarree())
    ax.plot([-0.08, 132], [51.53, 43.17], transform=ccrs.PlateCarree())
    ax.plot([-0.08, 132], [51.53, 43.17], transform=ccrs.Geodetic())

    plt.show()


if __name__ == '__main__':
    main()
```

#### Traceback

```
Traceback (most recent call last):
  File "/Users/crotwell/Code/GitHub/cartopy/testgeodetic/test.py", line 25, in <module>
    main()
  File "/Users/crotwell/Code/GitHub/cartopy/testgeodetic/test.py", line 18, in main
    ax.plot([-0.08, 132], [51.53, 43.17], transform=ccrs.PlateCarree())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cartopytest/lib/python3.12/site-packages/matplotlib/axes/_axes.py", line 1781, in plot
    self.add_line(line)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cartopytest/lib/python3.12/site-packages/matplotlib/axes/_base.py", line 2339, in add_line
    self._update_line_limits(line)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cartopytest/lib/python3.12/site-packages/matplotlib/axes/_base.py", line 2378, in _update_line_limits
    na_path, _ = line_trans_path.get_transformed_path_and_affine()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cartopytest/lib/python3.12/site-packages/matplotlib/transforms.py", line 2793, in get_transformed_path_and_affine
    self._revalidate()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cartopytest/lib/python3.12/site-packages/matplotlib/transforms.py", line 2769, in _revalidate
    self._transform.transform_path_non_affine(self._path)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cartopytest/lib/python3.12/site-packages/matplotlib/transforms.py", line 2445, in transform_path_non_affine
    return self._a.transform_path_non_affine(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cartopytest/lib/python3.12/site-packages/cartopy/mpl/geoaxes.py", line 175, in transform_path_non_affine
    geoms = cpatch.path_to_geos(src_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cartopytest/lib/python3.12/site-packages/cartopy/mpl/patch.py", line 210, in path_to_geos
    geom_collection = [sgeom.MultiLineString(geom_collection)]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cartopytest/lib/python3.12/site-packages/shapely/geometry/multilinestring.py", line 60, in __new__
    return shapely.multilinestrings(subs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cartopytest/lib/python3.12/site-packages/shapely/decorators.py", line 77, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cartopytest/lib/python3.12/site-packages/shapely/creation.py", line 393, in multilinestrings
    return lib.create_collection(geometries, typ, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ufunc 'create_collection' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

```

<details>
 <summary>Full environment definition</summary>

### Operating system
OSX 14.6.1 and Ubuntu 24.04

### Cartopy version
0.23.0

### conda list

```
# packages in environment at /opt/homebrew/Caskroom/miniforge/base/envs/cartopytest:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h99b78c6_7    conda-forge
ca-certificates           2024.7.4             hf0a4a13_0    conda-forge
cartopy                   0.23.0                   pypi_0    pypi
certifi                   2024.7.4                 pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
libexpat                  2.6.2                hebf3989_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libsqlite                 3.46.0               hfb93653_0    conda-forge
libzlib                   1.3.1                hfb2fe0b_1    conda-forge
matplotlib                3.9.2                    pypi_0    pypi
ncurses                   6.5                  hb89a1cb_0    conda-forge
numpy                     2.1.0                    pypi_0    pypi
openssl                   3.3.1                hfb2fe0b_2    conda-forge
packaging                 24.1                     pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2               pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.2                    pypi_0    pypi
pyproj                    3.6.1                    pypi_0    pypi
pyshp                     2.3.1                    pypi_0    pypi
python                    3.12.5          h30c5eda_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
readline                  8.2                  h92ec313_1    conda-forge
scipy                     1.14.0                   pypi_0    pypi
setuptools                72.1.0             pyhd8ed1ab_0    conda-forge
shapely                   2.0.5                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
tk                        8.6.13               h5083fa2_1    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
```

### pip list

```
Package         Version
--------------- -----------
Cartopy         0.23.0
certifi         2024.7.4
contourpy       1.2.1
cycler          0.12.1
fonttools       4.53.1
kiwisolver      1.4.5
matplotlib      3.9.2
numpy           2.1.0
packaging       24.1
pillow          10.4.0
pip             24.2
pyparsing       3.1.2
pyproj          3.6.1
pyshp           2.3.1
python-dateutil 2.9.0.post0
scipy           1.14.0
setuptools      72.1.0
shapely         2.0.5
six             1.16.0
wheel           0.44.0
```

</details>

**Comment by crotwell** [comment]
possibly related or similar: https://github.com/shapely/shapely/issues/2098

**Comment by dopplershift** [comment]
Looks pretty similar. I'd try installing Shapely 2.0.6 (which is now out) and see if that fixes it.

**Comment by crotwell** [comment]
shapely 2.0.6 seems to have fixed it. Thanks...
