### ISSUE TITLE
 WMS rendering: Bounding box coordinate 0 is not parsable:np.float64

### ISSUE THREAD

**Issue by juhi24** [SciTools/cartopy#2472]
### Description

getmap wants ax extent as `float` instead of `numpy.float64`. However, [this way](https://github.com/SciTools/cartopy/blob/97c6a6488d2edfd4780ac2d8df7b0014560e4917/lib/cartopy/mpl/slippy_image_artist.py#L56) of splitting a numpy array gives numpy floats. I'm writing a minimal bug report since the problem is quite simple. I can fix this.

#### Traceback

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.13/tkinter/__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "/usr/lib64/python3.13/tkinter/__init__.py", line 862, in callit
    func(*args)
    ~~~~^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/backends/_backend_tk.py", line 271, in idle_draw
    self.draw()
    ~~~~~~~~~^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/backends/backend_tkagg.py", line 10, in draw
    super().draw()
    ~~~~~~~~~~~~^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/backends/backend_agg.py", line 387, in draw
    self.figure.draw(self.renderer)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/figure.py", line 3162, in draw
    mimage._draw_list_compositing_images(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        renderer, self, artists, self.suppressComposite)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
    ~~~~~~^^^^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/cartopy/mpl/geoaxes.py", line 524, in draw
    return super().draw(renderer=renderer, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/axes/_base.py", line 3137, in draw
    mimage._draw_list_compositing_images(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        renderer, self, artists, self.figure.suppressComposite)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
    ~~~~~~^^^^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/cartopy/mpl/slippy_image_artist.py", line 58, in draw
    located_images = self.raster_source.fetch_raster(
        ax.projection, extent=[x1, x2, y1, y2],
        target_resolution=(window_extent.width, window_extent.height))
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/cartopy/io/ogc_clients.py", line 329, in fetch_raster
    located_images.append(self._image_and_extent(wms_proj, wms_srs,
                          ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
                                                 wms_extent,
                                                 ^^^^^^^^^^^
                                                 projection, extent,
                                                 ^^^^^^^^^^^^^^^^^^^
                                                 target_resolution))
                                                 ^^^^^^^^^^^^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/cartopy/io/ogc_clients.py", line 300, in _image_and_extent
    wms_image = self.service.getmap(layers=self.layers,
                                    srs=wms_srs,
    ...<2 lines>...
                                    format='image/png',
                                    **self.getmap_extra_kwargs)
  File "/home/tiira/.virtualenvs/visrad/lib/python3.13/site-packages/owslib/map/wms130.py", line 321, in getmap
    raise ServiceException(err_message)
owslib.util.ServiceException: java.lang.IllegalArgumentException: Bounding box coordinate 0 is not parsable:np.float64(100.0)
Bounding box coordinate 0 is not parsable:np.float64(100.0)
+proj=utm +ellps=GRS80 +units=m +zone=35 +no_defs +type=crs
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.13/tkinter/__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "/usr/lib64/python3.13/tkinter/__init__.py", line 862, in callit
    func(*args)
    ~~~~^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/backends/_backend_tk.py", line 271, in idle_draw
    self.draw()
    ~~~~~~~~~^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/backends/backend_tkagg.py", line 10, in draw
    super().draw()
    ~~~~~~~~~~~~^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/backends/backend_agg.py", line 387, in draw
    self.figure.draw(self.renderer)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/figure.py", line 3162, in draw
    mimage._draw_list_compositing_images(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        renderer, self, artists, self.suppressComposite)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
    ~~~~~~^^^^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/cartopy/mpl/geoaxes.py", line 524, in draw
    return super().draw(renderer=renderer, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/axes/_base.py", line 3137, in draw
    mimage._draw_list_compositing_images(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        renderer, self, artists, self.figure.suppressComposite)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
    ~~~~~~^^^^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/cartopy/mpl/slippy_image_artist.py", line 58, in draw
    located_images = self.raster_source.fetch_raster(
        ax.projection, extent=[x1, x2, y1, y2],
        target_resolution=(window_extent.width, window_extent.height))
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/cartopy/io/ogc_clients.py", line 329, in fetch_raster
    located_images.append(self._image_and_extent(wms_proj, wms_srs,
                          ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
                                                 wms_extent,
                                                 ^^^^^^^^^^^
                                                 projection, extent,
                                                 ^^^^^^^^^^^^^^^^^^^
                                                 target_resolution))
                                                 ^^^^^^^^^^^^^^^^^^
  File "/home/tiira/.virtualenvs/visrad/lib64/python3.13/site-packages/cartopy/io/ogc_clients.py", line 300, in _image_and_extent
    wms_image = self.service.getmap(layers=self.layers,
                                    srs=wms_srs,
    ...<2 lines>...
                                    format='image/png',
                                    **self.getmap_extra_kwargs)
  File "/home/tiira/.virtualenvs/visrad/lib/python3.13/site-packages/owslib/map/wms130.py", line 321, in getmap
    raise ServiceException(err_message)
owslib.util.ServiceException: java.lang.IllegalArgumentException: Bounding box coordinate 0 is not parsable:np.float64(100.0)
Bounding box coordinate 0 is not parsable:np.float64(100.0)
```

<details>
 <summary>Full environment definition</summary>

### Operating system
Linux/Fedora 41 Workstation

### Cartopy version
0.24.1

</details>

**Comment by QuLogic** [comment]
> owslib.util.ServiceException: java.lang.IllegalArgumentException: Bounding box coordinate 0 is not parsable:np.float64(-50186.32573271438)
> Bounding box coordinate 0 is not parsable:np.float64(-50186.32573271438)

This looks like a bug in OWSLib; it's converting the `np.float64` into a string to pass to the service incorrectly.

**Comment by juhi24** [comment]
Yes, I intend to rise this soon on owslib side in any case. Thanks for doing the research on what needs to be done on that side.

**Comment by juhi24** [comment]
This is now fixed upstream.
