### ISSUE TITLE
SystemError: error return without exception set

### ISSUE THREAD

**Issue by mikewalker92** [SciTools/cartopy#322]
```
import iris
import cartopy
import matplotlib.pyplot as plt
import iris.quickplot as qplt
import cartopy.crs as ccrs


cube = iris.load_cube(iris.sample_data_path('air_temp.pp'))

plt.axes(projection=ccrs.NorthPolarStereo())

qplt.contourf(cube)

plt.gca().gridlines()

#plt.gca().set_global()

plt.show()
```

The code above produces the following when run;

```
ValueError: zero-size array to fmin.reduce without identity
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/sci/lib/python2.7/lib-tk/Tkinter.py", line 1410, in __call__
    return self.func(*args)
  File "/usr/local/sci/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 276, in resize
    self.show()
  File "/usr/local/sci/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 348, in draw
    FigureCanvasAgg.draw(self)
  File "/usr/local/sci/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 439, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/sci/lib/python2.7/site-packages/matplotlib/artist.py", line 54, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/sci/lib/python2.7/site-packages/matplotlib/figure.py", line 999, in draw
    func(*args)
  File "/usr/local/sci/lib/python2.7/site-packages/matplotlib/artist.py", line 54, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/net/home/h04/mwalker/Git/cartopy/lib/cartopy/mpl/geoaxes.py", line 279, in draw
    gl._draw_gridliner(background_patch=self.background_patch)
  File "/net/home/h04/mwalker/Git/cartopy/lib/cartopy/mpl/gridliner.py", line 280, in _draw_gridliner
    background_patch=background_patch)
  File "/net/home/h04/mwalker/Git/cartopy/lib/cartopy/mpl/gridliner.py", line 428, in _axes_domain
    x_range = np.nanmin(inside[:, 0]), np.nanmax(inside[:, 0])
  File "/usr/local/sci/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1507, in nanmin
    return np.fmin.reduce(a.flat)
SystemError: error return without exception set
```

If however, this code is run with the set_global line uncommented, then the code will execute correctly. Further, if the code is run with the gridlines() line commented out, then the code will also run, but the plot will be a tiny plot, as descibed in #321. 

It therefore seems that the issue may be due to an inability to add grid lines to an object that is as small as what is being debt with here (less than 1 pixel).

If this is the root of the problem, then a solution to #321 would prevent this error from arising, but it may still be worth catching.

**Comment by pelson** [comment]
Fixed with #548.
