### ISSUE TITLE
natural_earth throws "urllib2.HTTPError: HTTP Error 404: Not Found"

### ISSUE THREAD

**Issue by haginile** [SciTools/cartopy#487]
When calling

    shpfilename = shpreader.natural_earth(resolution='110m', category='cultural', name='admin_0_countries')

I received the following error:

    /usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cartopy/io/__init__.py:261: DownloadWarning: Downloading: http://www.nacis.org/naturalearth/110m/cultural/ne_110m_admin_0_countries.zip
      warnings.warn('Downloading: {}'.format(url), DownloadWarning)
    Traceback (most recent call last):
      File "/SHFuse/Google Drive/Workspace/GEMLib2/Mapping/mapping.py", line 18, in <module>
        name='admin_0_countries')
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cartopy/io/shapereader.py", line 246, in natural_earth
        return ne_downloader.path(format_dict)
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cartopy/io/__init__.py", line 223, in path
        result_path = self.acquire_resource(target_path, format_dict)
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cartopy/io/shapereader.py", line 301, in acquire_resource
        shapefile_online = self._urlopen(url)
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cartopy/io/__init__.py", line 262, in _urlopen
        return urlopen(url)
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
        return _opener.open(url, data, timeout)
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
        response = meth(req, response)
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 442, in error
        result = self._call_chain(*args)
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
        result = func(*args)
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 629, in http_error_302
        return self.parent.open(new, timeout=req.timeout)
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
        response = meth(req, response)
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
        return self._call_chain(*args)
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
        result = func(*args)
      File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 404: Not Found

Is there an easy way to override the url?

**Comment by rhattersley** [comment]
As noted in SciTools/iris#1510, this has cropped up again. Perhaps we should look to fix the URL to [v2.0](https://github.com/nvkelso/natural-earth-vector/raw/v2.0/zips/110m_physical/ne_110m_coastline.zip)?

**Comment by pelson** [comment]
> As noted in SciTools/iris#1510, this has cropped up again. Perhaps we should look to fix the URL to v2.0?

@esc24 and I just had a similar conversation and I agree. The concern is that eventually, given prior, it wouldn't surprise me if the v2.0 branch just disappeared as well :sob:.

**Comment by esc24** [comment]
Natural Earth have fixed their URLs (http://www.naturalearthdata.com/blog/downloads-are-404ing/) - can we move back to that URL?

**Comment by rhattersley** [comment]
I feel like we've had more issues with the naturalearthdata/nacis URLs.

**Comment by esc24** [comment]
We could use https://github.com/nvkelso/natural-earth-vector/tree/22699072eed29231fd2722dbb712e38b7c28e6a8 or stick to the 2.0 branch as you suggested.

**Comment by esc24** [comment]
> I feel like we've had more issues with the naturalearthdata/nacis URLs.

Fair enough @rhattersley. I opened an issue https://github.com/nvkelso/natural-earth-vector/issues/129 which has a clear reply worth reading.

**Comment by rhattersley** [comment]
Looks like naturalearthdata/nacis it is then.

**Comment by QuLogic** [comment]
I think we can close this one.
