### ISSUE TITLE
Error when plotting contourf with orthographic projection

### ISSUE THREAD

**Issue by shoyer** [SciTools/cartopy#647]
The following code works with other projections, but not orthographic. Any thoughts?

``` python
import cartopy.crs as ccrs
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

latitude = np.arange(90, -90.75, -0.75)
longitude = np.arange(0, 360, 0.75)
data = np.arange(241 * 480).reshape(241, 480)

# ax = plt.axes(projection=ccrs.Mollweide())
ax = plt.axes(projection=ccrs.Orthographic())
ax.contourf(longitude, latitude, data, transform=ccrs.PlateCarree())
ax.coastlines()
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/Users/shoyer/miniconda/envs/santa-maria/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)
    328                 pass
    329             else:
--> 330                 return printer(obj)
    331             # Finally look for special method names
    332             method = _safe_get_formatter_method(obj, self.print_method)

/Users/shoyer/miniconda/envs/santa-maria/lib/python2.7/site-packages/IPython/core/pylabtools.pyc in <lambda>(fig)
    205 
    206     if 'png' in formats:
--> 207         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    208     if 'retina' in formats or 'png2x' in formats:
    209         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

/Users/shoyer/miniconda/envs/santa-maria/lib/python2.7/site-packages/IPython/core/pylabtools.pyc in print_figure(fig, fmt, bbox_inches, **kwargs)
    115 
    116     bytes_io = BytesIO()
--> 117     fig.canvas.print_figure(bytes_io, **kw)
    118     data = bytes_io.getvalue()
    119     if fmt == 'svg':

/Users/shoyer/miniconda/envs/santa-maria/lib/python2.7/site-packages/matplotlib/backend_bases.pyc in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2156                     orientation=orientation,
   2157                     dryrun=True,
-> 2158                     **kwargs)
   2159                 renderer = self.figure._cachedRenderer
   2160                 bbox_inches = self.figure.get_tightbbox(renderer)

/Users/shoyer/miniconda/envs/santa-maria/lib/python2.7/site-packages/matplotlib/backends/backend_agg.pyc in print_png(self, filename_or_obj, *args, **kwargs)
    519 
    520     def print_png(self, filename_or_obj, *args, **kwargs):
--> 521         FigureCanvasAgg.draw(self)
    522         renderer = self.get_renderer()
    523         original_dpi = renderer.dpi

/Users/shoyer/miniconda/envs/santa-maria/lib/python2.7/site-packages/matplotlib/backends/backend_agg.pyc in draw(self)
    467 
    468         try:
--> 469             self.figure.draw(self.renderer)
    470         finally:
    471             RendererAgg.lock.release()

/Users/shoyer/miniconda/envs/santa-maria/lib/python2.7/site-packages/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     57     def draw_wrapper(artist, renderer, *args, **kwargs):
     58         before(artist, renderer)
---> 59         draw(artist, renderer, *args, **kwargs)
     60         after(artist, renderer)
     61 

/Users/shoyer/miniconda/envs/santa-maria/lib/python2.7/site-packages/matplotlib/figure.pyc in draw(self, renderer)
   1083         dsu.sort(key=itemgetter(0))
   1084         for zorder, a, func, args in dsu:
-> 1085             func(*args)
   1086 
   1087         renderer.close_group('figure')

/Users/shoyer/miniconda/envs/santa-maria/lib/python2.7/site-packages/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     57     def draw_wrapper(artist, renderer, *args, **kwargs):
     58         before(artist, renderer)
---> 59         draw(artist, renderer, *args, **kwargs)
     60         after(artist, renderer)
     61 

/Users/shoyer/miniconda/envs/santa-maria/lib/python2.7/site-packages/cartopy/mpl/geoaxes.pyc in draw(self, renderer, inframe)
    336         if self.outline_patch.reclip or self.background_patch.reclip:
    337             clipped_path = clip_path(self.outline_patch.orig_path,
--> 338                                      self.viewLim)
    339             self.outline_patch._path = clipped_path
    340             self.background_patch._path = clipped_path

/Users/shoyer/miniconda/envs/santa-maria/lib/python2.7/site-packages/cartopy/mpl/clip_path.pyc in clip_path(subject, clip_bbox)
    115 
    116         """
--> 117         return subject.clip_to_bbox(clip_bbox)
    118 else:
    119     def clip_path(subject, clip_bbox):

/Users/shoyer/miniconda/envs/santa-maria/lib/python2.7/site-packages/matplotlib/path.pyc in clip_to_bbox(self, bbox, inside)
    932         verts = _path.clip_path_to_rect(self, bbox, inside)
    933         paths = [Path(poly) for poly in verts]
--> 934         return self.make_compound_path(*paths)
    935 
    936 

/Users/shoyer/miniconda/envs/santa-maria/lib/python2.7/site-packages/matplotlib/path.pyc in make_compound_path(cls, *args)
    330         total_length = sum(lengths)
    331 
--> 332         vertices = np.vstack([x.vertices for x in args])
    333         vertices.reshape((total_length, 2))
    334 

/Users/shoyer/miniconda/envs/santa-maria/lib/python2.7/site-packages/numpy/core/shape_base.pyc in vstack(tup)
    226 
    227     """
--> 228     return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    229 
    230 def hstack(tup):

ValueError: need at least one array to concatenate
```

**Comment by pelson** [comment]
This is a mpl bug see: https://github.com/SciTools/cartopy/issues/318#issuecomment-77902494
Though I confess, it was probably my bug in the first place (inside matplotlib) :disappointed: 

Updating matplotlib would fix this, but equally, cartopy isn't tested against the v1.4 release at this point (on the TODO list).

**Comment by awickert** [comment]
I am using Matplotlib v. 1.4.2, and an array concatenation error still occurs. One perhaps-useful piece of information is that this error does not occur if I set the axis extent to remain within one hemisphere, e.g.,

```
ax = plt.axes(projection=ccrs.Orthographic(central_longitude=0, central_latitude=-90))
ax.set_extent([-180, 180, -90, -1], ccrs.PlateCarree())
```

The error that was thrown when I allow the extent to approach or cross the equator is:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1535, in __call__
    return self.func(*args)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 278, in resize
    self.show()
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 349, in draw
    FigureCanvasAgg.draw(self)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 469, in draw
    self.figure.draw(self.renderer)
  File "/usr/lib/python2.7/dist-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1079, in draw
    func(*args)
  File "/usr/lib/python2.7/dist-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/awickert/.local/lib/python2.7/site-packages/cartopy/mpl/geoaxes.py", line 338, in draw
    self.viewLim)
  File "/home/awickert/.local/lib/python2.7/site-packages/cartopy/mpl/clip_path.py", line 117, in clip_path
    return subject.clip_to_bbox(clip_bbox)
  File "/usr/lib/python2.7/dist-packages/matplotlib/path.py", line 936, in clip_to_bbox
    return self.make_compound_path(*paths)
  File "/usr/lib/python2.7/dist-packages/matplotlib/path.py", line 332, in make_compound_path
    vertices = np.vstack([x.vertices for x in args])
  File "/home/awickert/.local/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
```

Hope this helps -- and that someone has some idea of what is going on!

**Comment by awickert** [comment]
UPDATE: I updated Matplotlib to have the changes shown in this ticket: matplotlib/matplotlib#4107. However, all that happened at first is that instead of an error being thrown, what I thought to be a blank plot was generated. After a lot of banging my head against a wall, I accidentally zoomed around on one of these plots, and discovered that after a lot of zooming out and re-centering, the desired map was created, but simply was not centered in the plot. I am really confused as to why this is the case, but thought that this is another piece of useful information... and perhaps worth its own ticket.

**Comment by pelson** [comment]
Thanks @awickert - really useful diagnosis. I'll spend a little time today putting together a cartopy release, and will take a look to see if I can get cartopy playing nicely in this situation.

**Comment by awickert** [comment]
Hi @pelson -- just pinging here to see if you've had any luck with this. I'm working on re-tooling my GRASS GIS Python plotting tool, currently a bit of a hack: https://github.com/awickert/GRASSplot

**Comment by pelson** [comment]
I can confirm that this exception no longer occurs with matplotlib 1.5. The workaround that @awickert has given can be generalised a little with the addition of:

```
ax.relim()
ax.autoscale_view()
```

For example:

```
import cartopy.crs as ccrs
import numpy as np
import matplotlib.pyplot as plt

latitude = np.arange(90, -90.75, -0.75)
longitude = np.arange(0, 360.75, 0.75)
data = np.cos(np.deg2rad(latitude[:, np.newaxis])) + np.sin(np.deg2rad(longitude))

# ax = plt.axes(projection=ccrs.Mollweide())
ax = plt.axes(projection=ccrs.Orthographic())
ax.contourf(longitude, latitude, data, transform=ccrs.PlateCarree())
ax.coastlines()

ax.relim()
ax.autoscale_view()

plt.show()
```

![figure_1](https://cloud.githubusercontent.com/assets/810663/12136304/4b8875f0-b43e-11e5-922e-b220cfc77247.png)

We need to look into why the relim and autoscale_view are now needed in v1.5 of matplotlib when they weren't in v1.3. Given the bug that emanated, I suspect we can rule out cartopy supporting matplotlib v1.4 altogether.

**Comment by pelson** [comment]
I imagine this will be part of #354.

**Comment by PBrockmann** [comment]
Use of  
```
ax.set_global() 
```
instead of  
```
ax.relim()
ax.autoscale_view()
```
makes also possible the plot.

```
import cartopy.crs as ccrs
import numpy as np
import matplotlib.pyplot as plt

latitude = np.arange(90, -90.75, -0.75)
longitude = np.arange(0, 360.75, 0.75)
data = np.cos(np.deg2rad(latitude[:, np.newaxis])) + np.sin(np.deg2rad(longitude))

ax = plt.axes(projection=ccrs.Orthographic())
ax.contourf(longitude, latitude, data, transform=ccrs.PlateCarree())
ax.coastlines()

ax.set_global()

plt.show()
```

**Comment by pelson** [comment]
Resolved with update to matplotlib.
