### ISSUE TITLE
Cartopy on Windows64+Python 3.5

### ISSUE THREAD

**Issue by ocefpaf** [SciTools/cartopy#699]
Cartopy  builds but fails to pass the conda test for saving a figure. (Click [here](https://ci.appveyor.com/project/comtbot/conda-recipes/build/1.0.1436/job/w2bex7jxxp7k19r6) for the full log.)

```python
===== testing package: cartopy-0.13.0-np110py35_2 =====
import: 'cartopy'
import: 'cartopy.mpl.geoaxes'
import: 'cartopy.crs'
running run_test.py
Exception ignored in: 'cartopy.trace.get_geos_context_handle'
OverflowError: Python int too large to convert to C long
Traceback (most recent call last):
  File "C:\conda\conda-bld\test-tmp_dir\run_test.py", line 43, in <module>
    plt.savefig('working.png')
  File "C:\conda\envs\_test\lib\site-packages\matplotlib\pyplot.py", line 577, in savefig
    res = fig.savefig(*args, **kwargs)
  File "C:\conda\envs\_test\lib\site-packages\matplotlib\figure.py", line 1476, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "C:\conda\envs\_test\lib\site-packages\matplotlib\backend_bases.py", line 2211, in print_figure
    **kwargs)
  File "C:\conda\envs\_test\lib\site-packages\matplotlib\backends\backend_agg.py", line 521, in print_png
    FigureCanvasAgg.draw(self)
  File "C:\conda\envs\_test\lib\site-packages\matplotlib\backends\backend_agg.py", line 469, in draw
    self.figure.draw(self.renderer)
  File "C:\conda\envs\_test\lib\site-packages\matplotlib\artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\conda\envs\_test\lib\site-packages\matplotlib\figure.py", line 1085, in draw
    func(*args)
  File "C:\conda\envs\_test\lib\site-packages\matplotlib\artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\conda\envs\_test\lib\site-packages\cartopy\mpl\geoaxes.py", line 359, in draw
    inframe=inframe)
  File "C:\conda\envs\_test\lib\site-packages\matplotlib\artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\conda\envs\_test\lib\site-packages\matplotlib\axes\_base.py", line 2110, in draw
    a.draw(renderer)
  File "C:\conda\envs\_test\lib\site-packages\matplotlib\artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\conda\envs\_test\lib\site-packages\cartopy\mpl\feature_artist.py", line 103, in draw
    extent = ax.get_extent(feature_crs)
  File "C:\conda\envs\_test\lib\site-packages\cartopy\mpl\geoaxes.py", line 501, in get_extent
    p = self._get_extent_geom(crs)
  File "C:\conda\envs\_test\lib\site-packages\cartopy\mpl\geoaxes.py", line 547, in _get_extent_geom
    self.projection)
  File "C:\conda\envs\_test\lib\site-packages\cartopy\crs.py", line 172, in project_geometry
    return getattr(self, method_name)(geometry, src_crs)
  File "C:\conda\envs\_test\lib\site-packages\cartopy\crs.py", line 315, in _project_polygon
    p_rings, p_mline = self._project_linear_ring(src_ring, src_crs)
  File "C:\conda\envs\_test\lib\site-packages\cartopy\crs.py", line 192, in _project_linear_ring
    src_crs, self)
  File "lib\cartopy\trace.pyx", line 109, in cartopy.trace.project_linear (lib/cartopy\trace.cpp:1148)
  File "lib\cartopy\trace.pyx", line 71, in cartopy.trace.geos_from_shapely (lib/cartopy\trace.cpp:851)
OverflowError: Python int too large to convert to C long
TESTS FAILED: cartopy-0.13.0-np110py35_2
Command exited with code 1
```

**Comment by QuLogic** [comment]
There are actually several issues with 3.5 (#676) and the error you see is an intermittent one which is not Python 3 specific (#680).

**Comment by ocefpaf** [comment]
> intermittent

It was not intermittent in case :disappointed: 

But now there is a xref to #676.  Thanks!
