### ISSUE TITLE
Installing cartopy with pip fails - no cython found and is not a requirement

### ISSUE THREAD

**Issue by ispmarin** [SciTools/cartopy#725]
Installing cartopy on an Ubuntu 14.04 with Python 3 using pip

    pip install cartopy

I get the error

```
Collecting cartopy
  Using cached Cartopy-0.13.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-_hya0obf/cartopy/setup.py", line 36, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named 'Cython'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_hya0obf/cartopy/setup.py", line 38, in <module>
        raise ImportError('Cython 0.15.1+ is required to install cartopy.')
    ImportError: Cython 0.15.1+ is required to install cartopy.
```

I have to manually install `cython` on the same virtualenv:

    pip install cython

and after that I have to issue again the `cartopy` install command:

    pip install cartopy

and now works.

**Comment by ispmarin** [comment]
Thanks!
